import type { TacticalStyle } from '@/lib/analyzer';
import type { TeamDiagnosis } from '@/modules/core/centralIntelligence';
import {getConfirmedMatchMarkers,getVisibleMatchMarkers,isAttackEvent,isDefenseEvent,type MatchEventKind,type MatchEventMarker,type MatchPhase,type MatchTrainerSession} from './matchTrainerEngine';

export const MATCH_VISION_R482_VERSION='40.80-r482-match-vision-v2';
export const MATCH_VISION_DIMENSIONS_R482=['ZONES','LINES','ISOLATION','FORCED_PASSES','POSSESSION_LOSSES','INVOLVEMENT','SPACE_OCCUPATION','PROGRESSION','PRESSING','TRANSITIONS','FINISHING','OFF_BALL_MOVEMENT'] as const;
export type MatchVisionDimensionR482=(typeof MATCH_VISION_DIMENSIONS_R482)[number];
export type MatchVisionEvidenceStateR482='INSUFFICIENT'|'PROVISIONAL';

const POSITIVE_KINDS=new Set<MatchEventKind>(['good-transition','good-build-up','good-play','goal-for','interception']);
const TRANSITION_KINDS=new Set<MatchEventKind>(['dangerous-turnover','late-recomposition','good-transition','lost-counterattack','second-ball-failure']);
const PHASE_ORDER:MatchPhase[]=['build-up','attack','defensive-transition','defense','set-piece','game-management','unknown'];
const PHASE_LABELS:Record<MatchPhase,string>={'build-up':'Construção',attack:'Ataque','defensive-transition':'Transição defensiva',defense:'Defesa','set-piece':'Bola parada','game-management':'Gestão',unknown:'Não confirmado'};
const DIMENSION_KINDS:Partial<Record<MatchVisionDimensionR482,readonly MatchEventKind[]>>={LINES:['defender-out-of-line'],ISOLATION:['pressured-receiver','no-triangulation','double-defender'],FORCED_PASSES:['pass-error','delayed-pass','pressured-receiver','late-release','command-pass-early'],POSSESSION_LOSSES:['dangerous-turnover','pass-error','dangerous-dribble','lost-counterattack'],SPACE_OCCUPATION:['no-triangulation','fullback-corridor-open','central-corridor-open','double-defender'],PROGRESSION:['good-build-up','predictable-attack','no-triangulation','late-release'],PRESSING:['pressing-error','pressured-receiver','interception','wrong-double-mark'],FINISHING:['forced-shot','unbalanced-shot','goal-for'],OFF_BALL_MOVEMENT:['defender-out-of-line','late-recomposition','fullback-corridor-open','central-corridor-open']};
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,Math.round(v)));
const severityWeight=(m:MatchEventMarker)=>m.severity==='critical'?5:m.severity==='high'?4:m.severity==='medium'?3:m.severity==='low'?2:m.severity==='positive'?1:2;
function normalizedPhase(m:MatchEventMarker):MatchPhase{if(m.phase&&PHASE_ORDER.includes(m.phase))return m.phase;if(isAttackEvent(m.kind))return'attack';if(isDefenseEvent(m.kind))return'defense';return TRANSITION_KINDS.has(m.kind)?'defensive-transition':'unknown'}
const markerLabel=(k:MatchEventKind)=>k.replaceAll('-',' ').replace(/\b\w/g,l=>l.toLocaleUpperCase('pt-BR'));
function dominantPhase(ms:MatchEventMarker[]):MatchPhase{if(!ms.length)return'unknown';const c=new Map<MatchPhase,number>();for(const m of ms){const p=normalizedPhase(m);c.set(p,(c.get(p)??0)+1)}return[...c].sort((a,b)=>b[1]-a[1]||PHASE_ORDER.indexOf(a[0])-PHASE_ORDER.indexOf(b[0]))[0]?.[0]??'unknown'}
const hasAnnotation=(m:MatchEventMarker,k:readonly NonNullable<MatchEventMarker['annotations']>[number]['kind'][])=>(m.annotations?.some(a=>k.includes(a.kind)))??false;
function supports(m:MatchEventMarker,d:MatchVisionDimensionR482){if(d==='ZONES')return['fullback-corridor-open','central-corridor-open'].includes(m.kind)||hasAnnotation(m,['open-space','danger-zone']);if(d==='LINES')return(DIMENSION_KINDS.LINES?.includes(m.kind)??false)||hasAnnotation(m,['blocked-line','recommended-line']);if(d==='INVOLVEMENT')return Boolean(m.playerId||m.playerLabel||m.playerCardFingerprint||m.playerHistoryId);if(d==='TRANSITIONS')return TRANSITION_KINDS.has(m.kind);if(d==='SPACE_OCCUPATION')return(DIMENSION_KINDS.SPACE_OCCUPATION?.includes(m.kind)??false)||hasAnnotation(m,['open-space','danger-zone','hold-position']);if(d==='OFF_BALL_MOVEMENT')return(DIMENSION_KINDS.OFF_BALL_MOVEMENT?.includes(m.kind)??false)||hasAnnotation(m,['wrong-arrow','correct-arrow','hold-position']);return DIMENSION_KINDS[d]?.includes(m.kind)??false}
function buildDimensionCoverage(ms:MatchEventMarker[]){return MATCH_VISION_DIMENSIONS_R482.map(d=>{const x=ms.filter(m=>supports(m,d)).sort((a,b)=>a.atMs-b.atMs||a.id.localeCompare(b.id));return{dimension:d,evidenceCount:x.length,confidence:x.length?clamp(x.reduce((s,m)=>s+clamp(Number(m.confidence||0)),0)/x.length):0,markerIds:x.map(m=>m.id)}})}
const segmentLabel=(i:number,n:number)=>i===0?'Início':i===n-1?'Final':i<n/2?'1ª metade':'2ª metade';
function buildTimeline(ms:MatchEventMarker[],durationMs:number){const n=durationMs>=3600000?8:durationMs>=1500000?6:4,d=Math.max(durationMs,1),span=d/n;return Array.from({length:n},(_,index)=>{const startMs=Math.round(index*span),endMs=index===n-1?Math.round(d):Math.round((index+1)*span),x=ms.filter(m=>m.atMs>=startMs&&m.atMs<=endMs),positiveEvents=x.filter(m=>POSITIVE_KINDS.has(m.kind)).length,riskEvents=x.length-positiveEvents,attackEvents=x.filter(m=>isAttackEvent(m.kind)).length,defenseEvents=x.filter(m=>isDefenseEvent(m.kind)).length,transitionEvents=x.filter(m=>TRANSITION_KINDS.has(m.kind)).length,impact=x.reduce((s,m)=>s+severityWeight(m),0);return{index,startMs,endMs,label:segmentLabel(index,n),dominantPhase:dominantPhase(x),intensity:clamp(Math.min(100,impact*12+x.length*5)),confirmedEvents:x.length,positiveEvents,riskEvents,attackEvents,defenseEvents,transitionEvents}})}
function buildCriticalWindows(ms:MatchEventMarker[],durationMs:number){const all=ms.filter(m=>!POSITIVE_KINDS.has(m.kind)).map((m,index)=>{const x=ms.filter(a=>Math.abs(a.atMs-m.atMs)<=15000);return{id:`vision-window-${index}-${Math.round(m.atMs)}`,centerMs:m.atMs,startMs:Math.max(0,m.clipStartMs??m.atMs-8000),endMs:Math.min(Math.max(durationMs,m.atMs+1),m.clipEndMs??m.atMs+10000),score:clamp(severityWeight(m)*16+Math.max(0,x.length-1)*8+(m.repeated?10:0)),phase:normalizedPhase(m),title:m.title||markerLabel(m.kind),reason:m.why||m.detail||'Janela com evidência confirmada que merece revisão tática.',markerKinds:[...new Set(x.map(a=>a.kind))],confirmedEvents:x.length}}).sort((a,b)=>b.score-a.score||a.centerMs-b.centerMs),out:typeof all=[];for(const w of all){if(out.some(x=>Math.abs(x.centerMs-w.centerMs)<12000))continue;out.push(w);if(out.length===5)break}return out}
function buildPatterns(ms:MatchEventMarker[]){const g=new Map<MatchEventKind,MatchEventMarker[]>();for(const m of ms){if(POSITIVE_KINDS.has(m.kind))continue;const x=g.get(m.kind)??[];x.push(m);g.set(m.kind,x)}return[...g].map(([kind,x])=>({kind,label:x[0]?.title||markerLabel(kind),occurrences:x.length,impact:clamp(x.reduce((s,m)=>s+severityWeight(m),0)*12),moments:x.map(m=>m.atMs).sort((a,b)=>a-b),phase:dominantPhase(x)})).sort((a,b)=>b.occurrences-a.occurrences||b.impact-a.impact).slice(0,6)}
function buildPhaseBalance(ms:MatchEventMarker[]){return PHASE_ORDER.map(phase=>{const confirmedEvents=ms.filter(m=>normalizedPhase(m)===phase).length;return{phase,label:PHASE_LABELS[phase],confirmedEvents,share:ms.length?clamp(confirmedEvents/ms.length*100):0}}).filter(x=>x.confirmedEvents||x.phase==='unknown')}
function styleObservation(teamStyle:TacticalStyle,ms:MatchEventMarker[],team:TeamDiagnosis){const buildUp=ms.filter(m=>normalizedPhase(m)==='build-up').length,attack=ms.filter(m=>normalizedPhase(m)==='attack').length,transition=ms.filter(m=>normalizedPhase(m)==='defensive-transition').length,passRisks=ms.filter(m=>['pass-error','pressured-receiver','late-release','no-triangulation'].includes(m.kind)).length,positiveBuild=ms.filter(m=>m.kind==='good-build-up').length;if(!ms.length)return`Sem lances confirmados suficientes para comparar o comportamento observado com ${team.formation}.`;if(teamStyle==='POSSE_DE_BOLA')return positiveBuild>passRisks&&buildUp>0?'Os lances confirmados mostram sinais compatíveis com circulação e construção; preserve apoios curtos e confirme em mais partidas.':'A amostra confirmada ainda mostra interrupções na circulação ou pouca evidência de construção segura para validar plenamente o modelo de Posse de Bola.';if(teamStyle==='CONTRA_ATAQUE_RAPIDO'||teamStyle==='CONTRA_ATAQUE')return transition+attack>=buildUp?'A amostra confirmada concentra mais ações de transição/ataque do que de construção longa, coerente com um modelo vertical, sem implicar previsão de resultado.':'Os lances confirmados mostram mais construção do que aceleração; vale revisar se a execução está correspondendo ao modelo de contra-ataque configurado.';return`A leitura atual usa ${ms.length} lance(s) confirmado(s) para comparar execução e contexto do estilo configurado, sem alterar a tática automaticamente.`}
export function buildMatchVisionR482({session,team,teamStyle}:{session:MatchTrainerSession;team:TeamDiagnosis;teamStyle:TacticalStyle}){const visible=getVisibleMatchMarkers(session),confirmed=getConfirmedMatchMarkers(session),suggestedMarkers=visible.filter(m=>m.reviewStatus==='suggested').length,totalReviewable=confirmed.length+suggestedMarkers,reviewedCoverage=totalReviewable?clamp(confirmed.length/totalReviewable*100):0,durationMs=Math.max(Number(session.analysis?.durationMs||0),...confirmed.map(m=>m.atMs),0),videoQualityScore=clamp(Number(session.analysis?.qualityScore||0)),sampleCount=Number(session.analysis?.sampleCount||0),videoEvidence=session.analysis?Math.min(100,35+videoQualityScore*.45+Math.min(20,sampleCount/8)):0,confidence=clamp(Math.min(100,confirmed.length*11)*.48+reviewedCoverage*.22+videoEvidence*.2+(team.formation?10:0)),dimensionCoverage=buildDimensionCoverage(confirmed),completeness=clamp(dimensionCoverage.filter(x=>x.evidenceCount).length/MATCH_VISION_DIMENSIONS_R482.length*100),missingDimensions=dimensionCoverage.filter(x=>!x.evidenceCount).map(x=>x.dimension),timeline=buildTimeline(confirmed,durationMs),criticalWindows=buildCriticalWindows(confirmed,durationMs),recurringPatterns=buildPatterns(confirmed),phaseBalance=buildPhaseBalance(confirmed),positiveCount=confirmed.filter(m=>POSITIVE_KINDS.has(m.kind)).length,strengths=[positiveCount?`${positiveCount} jogada(s) positiva(s) confirmada(s) para repetir.`:null,reviewedCoverage>=70?`${reviewedCoverage}% dos momentos revisáveis já foram confirmados pelo usuário.`:null,timeline.some(s=>s.positiveEvents>s.riskEvents)?'Existe ao menos um trecho com mais evidências positivas do que riscos confirmados.':null].filter((x):x is string=>Boolean(x)),risks=[recurringPatterns[0]?.occurrences>=2?`Padrão recorrente: ${recurringPatterns[0].label} apareceu ${recurringPatterns[0].occurrences} vez(es).`:null,suggestedMarkers?`${suggestedMarkers} momento(s) automático(s) ainda aguardam confirmação e não entram como erro.`:null,confirmed.length<3?'Amostra confirmada pequena: use a leitura como hipótese de revisão, não como conclusão definitiva.':null,missingDimensions.length?`${missingDimensions.length} dimensão(ões) do Match Vision ainda estão sem evidência confirmada.`:null].filter((x):x is string=>Boolean(x)),possibleDelayCount=confirmed.filter(m=>m.kind==='possible-delay').length,freezeCount=Number(session.analysis?.possibleFreezeCount||0),connectionGuardrail=possibleDelayCount||freezeCount?`Há ${possibleDelayCount} marcação(ões) confirmada(s) de possível atraso e ${freezeCount} pausa(s) visual(is) detectada(s). Pausa visual isolada não prova lag; valide junto com sensação de comando e conexão.`:'Nenhuma evidência confirmada suficiente para atribuir problemas táticos à conexão. O Match Vision não chama pausa visual de lag automaticamente.';
 return{version:MATCH_VISION_R482_VERSION,mode:'READ_ONLY_MATCH_VISION' as const,confidence,evidenceState:(confirmed.length?'PROVISIONAL':'INSUFFICIENT') as MatchVisionEvidenceStateR482,completeness,definitive:false as const,dimensionCoverage,missingDimensions,configuredContext:{formation:team.formation,teamStyle},evidence:{durationMs,videoAnalyzed:Boolean(session.analysis),videoQualityScore,confirmedMarkers:confirmed.length,suggestedMarkers,reviewedCoverage,sampleCount},timeline,criticalWindows,recurringPatterns,phaseBalance,styleObservation:styleObservation(teamStyle,confirmed,team),connectionGuardrail,strengths,risks,authority:{readOnly:true as const,canConfirmMarkersAutomatically:false as const,canWriteTraining:false as const,canWriteSkills:false as const,canWriteImpetus:false as const,canOverrideR128:false as const,writesFinalCard:false as const,writesTop5:false as const,overallGerUsed:false as const,certifiedForFinalWrite:false as const},guardrails:['Somente lances confirmados entram nos padrões, fases, dimensões e janelas críticas; candidatos automáticos permanecem pendentes.','O Match Vision R482 não reconhece com certeza botões, identidade de todos os jogadores ou causa de lag sem confirmação externa.','A camada é observacional: não altera automaticamente formação, escalação, ficha, Top 5, Skills ou Ímpeto.','Uma única sessão/vídeo permanece PROVISIONAL, mesmo com cobertura ampla; não equivale a certificação final.','Dimensões sem marcador confirmado permanecem explicitamente ausentes; o motor não inventa observações.','Overall/GER não participa da autoridade do Match Vision.','A autoridade final das cartas permanece R119 → R126 → R128.']}}
export type MatchVisionDimensionCoverageR482=ReturnType<typeof buildDimensionCoverage>[number];
export type MatchVisionTimelineSegmentR482=ReturnType<typeof buildTimeline>[number];
export type MatchVisionCriticalWindowR482=ReturnType<typeof buildCriticalWindows>[number];
export type MatchVisionPatternR482=ReturnType<typeof buildPatterns>[number];
export type MatchVisionSnapshotR482=ReturnType<typeof buildMatchVisionR482>;
