'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { BarChart3, Brain, CheckCircle2, Clock3, Download, History, Pause, Play, Plus, RotateCcw, ShieldCheck, Target, Trophy, Users, Video, Wifi } from 'lucide-react';
import type { IntegratedPlayerRecord, MatchScenarioPlan, TeamDiagnosis } from '@/modules/core/centralIntelligence';
import type { TacticalStyle } from '@/lib/analyzer';
import { TrainingEvolutionCenter } from '@/modules/training/TrainingEvolutionCenter';
import { CompetitivePerformanceCenter } from './CompetitivePerformanceCenter';
import { MatchTrainerCenter } from './MatchTrainerCenter';
import { AntiDelayCenter } from '@/modules/performance/AntiDelayCenter';
import { SmartCoachCenter } from '@/modules/coaching/SmartCoachCenter';
import type { MatchValidationRecord } from '@/lib/appEvolution';
import { safeStorageGetJson, safeStorageSetJson } from '@/lib/safeLocalStorage';
import { PremiumScreenHero } from '@/components/PremiumScreenPrimitives';
import { OBSERVABILITY_EVENT, readFeatureFlags, type FeatureFlagState } from '@/modules/observability/observabilityEngine';
import { buildGameplayCalibrationBridgeR516 } from '@/modules/analysis/gameplayCalibrationBridgeR516';
import { buildRealMatchCalibrationEvidenceR518 } from '@/modules/analysis/realMatchCalibrationEvidenceR518';
import { buildBuildOutcomeCalibrationR460 } from './buildOutcomeCalibrationR460';
type MatchTab='gravar'|'competitivo'|'anti-delay'|'treinador'|'treinar'|'planejar'|'executar'|'analisar';
type TrainingLog={id:string;at:string;error:string;repetitions:number;seconds:number};
const TRAINING_LOG_KEY='buildmaster_guided_training_logs_v2739',WEEKLY_GOAL_KEY='buildmaster_weekly_training_goal_v2739';
const ERROR_OPTIONS=['Passe precipitado','Demora para soltar a bola','Marcação atrasada','Finalização forçada','Perdeu a compactação','Troca de jogador errada'];
function downloadText(name:string,content:string){const blob=new Blob([content],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}

export function MatchLaboratory({team,players,records,plans,teamStyle,onValidatePlayer,onOpenTeam}:{team:TeamDiagnosis;players:IntegratedPlayerRecord[];records:MatchValidationRecord[];plans:MatchScenarioPlan[];teamStyle:TacticalStyle;onValidatePlayer:(id:string)=>void;onOpenTeam:()=>void}){
const [tab,setTab]=useState<MatchTab>('competitivo'),[plan,setPlan]=useState<MatchScenarioPlan['id']>('control'),[running,setRunning]=useState(false),[seconds,setSeconds]=useState(0),[reps,setReps]=useState(0),[errors,setErrors]=useState<string[]>([]);
const [logs,setLogs]=useState<TrainingLog[]>(()=>safeStorageGetJson<TrainingLog[]>(TRAINING_LOG_KEY,[])),[goal,setGoal]=useState(()=>safeStorageGetJson<number>(WEEKLY_GOAL_KEY,3)),[flags,setFlags]=useState<FeatureFlagState>(()=>readFeatureFlags());
const panelRef=useRef<HTMLDivElement|null>(null),current=plans.find(p=>p.id===plan)??plans[0];
const queue=useMemo(()=>players.filter(p=>p.status==='completo').sort((a,b)=>a.matchCount-b.matchCount||b.efficiency-a.efficiency).slice(0,6),[players]);
const recent=useMemo(()=>[...records].sort((a,b)=>b.playedAt.localeCompare(a.playedAt)).slice(0,8),[records]);
const weekStart=useMemo(()=>{const now=new Date(),day=(now.getDay()+6)%7;now.setHours(0,0,0,0);now.setDate(now.getDate()-day);return now},[]),sessions=useMemo(()=>logs.filter(item=>new Date(item.at)>=weekStart).length,[logs,weekStart]);
const r518=useMemo(()=>buildRealMatchCalibrationEvidenceR518({origin:'PERSISTED_REAL',records,contexts:players.flatMap(({result})=>{const l=result.intelligentLearningR470,c=result.motorLabLifecycleR472;if(!result.buildOutcomeCalibrationR460||!l||!c)return[];const o=buildBuildOutcomeCalibrationR460(result,records);return[{contextKey:`${o.cardFingerprint}:${o.position}:${o.usageFunction}:${o.currentGenerationSignatureR464}`,outcomeR460:o,learningR470:l,lifecycleR472:c,bridgeR516:buildGameplayCalibrationBridgeR516({outcome:o,proposal:l.proposal})}]})}),[players,records]);
const tabs=[['gravar',Video,'Gravar e analisar',true],['competitivo',BarChart3,'Desempenho competitivo',true],['anti-delay',Wifi,'Central anti-delay',flags.antiDelay],['treinador',Brain,'Treinador inteligente',flags.smartCoach],['treinar',Trophy,'Treinos e evolução',true],['planejar',Target,'Planejar partida',true],['executar',Play,'Treino guiado',true],['analisar',History,'Histórico',true]] as const;
useEffect(()=>{if(!running)return;const timer=window.setInterval(()=>setSeconds(v=>v+1),1000);return()=>window.clearInterval(timer)},[running]);
useEffect(()=>{const refresh=()=>setFlags(readFeatureFlags());window.addEventListener(OBSERVABILITY_EVENT,refresh);return()=>window.removeEventListener(OBSERVABILITY_EVENT,refresh)},[]);
useEffect(()=>{if(tab==='anti-delay'&&!flags.antiDelay)setTab('competitivo');if(tab==='treinador'&&!flags.smartCoach)setTab('competitivo')},[flags.antiDelay,flags.smartCoach,tab]);
function selectTab(next:MatchTab){setTab(next);window.requestAnimationFrame(()=>panelRef.current?.scrollIntoView({behavior:'smooth',block:'start'}))}
function toggleError(error:string){setErrors(current=>current.includes(error)?current.filter(item=>item!==error):[...current,error])}
function saveTrainingLog(){const entry:TrainingLog={id:`training-${Date.now()}`,at:new Date().toISOString(),error:errors.join(' • ')||'Treino concluído sem erro marcado',repetitions:reps,seconds},next=[entry,...logs].slice(0,120);setLogs(next);safeStorageSetJson(TRAINING_LOG_KEY,next);setRunning(false);setSeconds(0);setReps(0);setErrors([]);selectTab('analisar')}
function changeGoal(value:number){setGoal(value);safeStorageSetJson(WEEKLY_GOAL_KEY,value)}
function exportWeeklyPlan(){const lines=['BuildMaster — Plano semanal',`Formação: ${team.formation}`,`Meta: ${goal} sessões`,`Realizadas: ${sessions}`,'',...plans.map(p=>`${p.label}: ${p.objective}\n- ${p.formationAdvice}\n- ${p.playerProfile}`),'','Erros recentes:',...logs.slice(0,10).map(item=>`${new Date(item.at).toLocaleString('pt-BR')} — ${item.error} — ${item.repetitions} repetições — ${item.seconds}s`)];downloadText(`buildmaster-plano-semanal-${new Date().toISOString().slice(0,10)}.txt`,lines.join('\n'))}
return <section className="v27-module v27-match-lab refined-match-lab bm2820-screen bm2820-performance-screen">
<PremiumScreenHero icon={Target} eyebrow="Centro de performance" title="Treino, partida e evolução em um só lugar." description="Escolha uma guia e o app leva você direto ao painel correspondente." badge={`${sessions}/${goal} sessões na semana`} actions={<><button type="button" className="elite-button" onClick={onOpenTeam}><Users size={17}/> Rever meu time</button><button type="button" onClick={exportWeeklyPlan}><Download size={17}/> Exportar semana</button></>} metrics={[{label:'Prontidão',value:team.globalScore,hint:`formação ${team.formation}`,tone:team.globalScore>=80?'positive':'warning'},{label:'Partidas',value:records.length,hint:'registros reais',tone:'accent'},{label:'Testes pendentes',value:queue.length,hint:'fichas na fila',tone:queue.length?'warning':'positive'},{label:'Treinos locais',value:logs.length,hint:'sessões salvas'}]}/>
<article className="v27-scenario-card luxury-panel" aria-label="Evidência real R510 / R518"><div className="v27-panel-heading"><div><p className="kicker"><ShieldCheck size={14}/> R137 • R518 read-only</p><h3>Evidência real R510 / R518</h3></div><span>{r518.status}</span></div><div className="v27-scenario-sections"><div><strong>Base real</strong><span>{r518.evidenceSummary.totalRecords}/24 partidas • {r518.evidenceSummary.distinctSessions}/6 sessões</span></div><div><strong>Cobertura</strong><span>{r518.evidenceSummary.readyContexts}/3 contextos • {r518.coverage.primitiveFamilies.length}/3 famílias • {r518.coverage.functionalContexts.length}/3 funções</span></div><div><strong>Pendências</strong><span>{r518.blockers.length} bloqueios • {r518.missingRequirements.length} requisitos</span></div></div><small>Somente leitura • {r518.authority.canCertifyR510?'R510 disponível':'R518 não certifica R510'} • sem aplicação automática • R119 → R126 → R128.</small></article>
<nav className="refined-match-tabs luxury-panel" role="tablist" aria-label="Etapas de treino e partida">{tabs.map(([id,Icon,label,visible])=>visible&&<button type="button" key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>selectTab(id)}><Icon size={17}/> {label}</button>)}{tab!=='treinar'&&<div className="refined-week-goal"><span>Meta semanal</span><select value={goal} onChange={event=>changeGoal(Number(event.target.value))}>{[2,3,4,5,6,7].map(value=><option key={value} value={value}>{value} sessões</option>)}</select><strong>{sessions}/{goal}</strong></div>}</nav>
<div ref={panelRef} className="bm34-tab-panel" role="tabpanel" aria-live="polite">
{tab==='gravar'&&<MatchTrainerCenter team={team} teamStyle={teamStyle}/>} {tab==='competitivo'&&<CompetitivePerformanceCenter formation={team.formation} teamStyle={teamStyle}/>} {tab==='anti-delay'&&flags.antiDelay&&<AntiDelayCenter/>} {tab==='treinador'&&flags.smartCoach&&<SmartCoachCenter team={team} teamStyle={teamStyle}/>} {tab==='treinar'&&<TrainingEvolutionCenter team={team} records={records} teamStyle={teamStyle}/>} 
{tab==='planejar'&&<><nav className="v27-scenario-tabs luxury-panel" aria-label="Cenários de partida">{plans.map(p=><button type="button" key={p.id} className={plan===p.id?'active':''} onClick={()=>setPlan(p.id)}>{p.label}</button>)}</nav><div className="v27-match-grid"><article className="v27-scenario-card luxury-panel"><div className="v27-panel-heading"><div><p className="kicker"><ShieldCheck size={14}/> Plano de jogo</p><h3>{current.label}</h3></div><span>{team.formation}</span></div><div className="v27-scenario-focus"><strong>Objetivo</strong><span>{current.objective}</span></div><div className="v27-scenario-sections"><div><strong>Ajuste da formação</strong><span>{current.formationAdvice}</span></div><div><strong>Perfil de jogador</strong><span>{current.playerProfile}</span></div><div><strong>Substituições</strong>{current.substitutions.map(item=><span key={item}><CheckCircle2 size={14}/>{item}</span>)}</div><div><strong>Riscos</strong>{current.risks.map(item=><span key={item}><Clock3 size={14}/>{item}</span>)}</div></div><button type="button" className="elite-button" onClick={()=>selectTab('executar')}><Play size={17}/> Iniciar treino guiado</button></article><aside className="v27-validation-queue luxury-panel"><div className="v27-panel-heading"><div><p className="kicker"><Trophy size={14}/> Próximos testes</p><h3>Fichas que precisam de partidas</h3></div><span>{queue.length}</span></div><div className="v27-player-list validation-list">{queue.map(p=><button type="button" key={p.id} onClick={()=>onValidatePlayer(p.id)}><div><strong>{p.name}</strong><span>{p.targetPosition} • {p.buildName}</span></div><small>{p.matchCount} jogo(s)</small></button>)}{!queue.length&&<div className="v27-empty"><CheckCircle2 size={25}/><strong>Nenhuma ficha aguardando teste</strong><span>Adicione novas cartas ou revise o histórico.</span></div>}</div></aside></div></>}
{tab==='executar'&&<section className="refined-training-execution luxury-panel"><div className="refined-training-clock"><Clock3 size={28}/><strong>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong><span>{running?'Treino em andamento':'Pronto para iniciar'}</span></div><div className="refined-training-controls"><button type="button" className="elite-button" onClick={()=>setRunning(v=>!v)}>{running?<Pause size={18}/>:<Play size={18}/>} {running?'Pausar':'Iniciar'}</button><button type="button" onClick={()=>setReps(v=>v+1)}><Plus size={18}/> Registrar repetição <strong>{reps}</strong></button><button type="button" onClick={()=>{setRunning(false);setSeconds(0);setReps(0)}}><RotateCcw size={18}/> Reiniciar</button></div><div className="refined-error-pad"><div><strong>Erros observados</strong><span>Marque com um toque durante o treino.</span></div>{ERROR_OPTIONS.map(error=><button type="button" key={error} className={errors.includes(error)?'active':''} aria-pressed={errors.includes(error)} onClick={()=>toggleError(error)}>{errors.includes(error)&&<CheckCircle2 size={15}/>} {error}</button>)}</div><button type="button" className="elite-button refined-finish-training" onClick={saveTrainingLog} disabled={!seconds&&!reps&&!errors.length}><CheckCircle2 size={18}/> Concluir e analisar</button></section>}
{tab==='analisar'&&<div className="refined-analysis-grid"><article className="v27-match-history luxury-panel"><div className="v27-panel-heading"><div><p className="kicker"><History size={14}/> Pós-jogo integrado</p><h3>Partidas recentes</h3></div><span>{records.length} total</span></div><div className="v27-history-table">{recent.map(record=><div key={record.id}><strong>{record.playerName}</strong><span>{new Date(record.playedAt).toLocaleDateString('pt-BR')} • {record.minutes} min</span><span>Nota {record.overallRating}/5</span><small>{record.tags.join(' • ')||'Sem problema marcado'}</small></div>)}{!recent.length&&<div className="v27-empty"><History size={25}/><strong>Sem partidas registradas</strong><span>Abra uma ficha na fila e registre o primeiro teste.</span></div>}</div></article><article className="luxury-panel refined-training-log"><div className="v27-panel-heading"><div><p className="kicker"><Clock3 size={14}/> Sessões locais</p><h3>Evolução por repetição</h3></div><span>{logs.length}</span></div>{logs.slice(0,12).map(item=><div key={item.id}><strong>{new Date(item.at).toLocaleDateString('pt-BR')}</strong><span>{item.repetitions} repetições • {Math.round(item.seconds/60)} min</span><small>{item.error}</small></div>)}{!logs.length&&<div className="v27-empty"><Clock3 size={25}/><strong>Nenhuma sessão concluída</strong><span>Use a guia Executar para registrar o primeiro treino.</span></div>}</article></div>}
</div></section>
}
