import type { AnalysisResult,ParsedCard,PositionCode,PositionProficiencyLevel,PositionUsageR416Analysis,PositionUsageR416Entry } from './analyzerDomain';
import { POSITION_PT } from './analyzerDomain';
import { fillAttributes,positionScore } from '@/modules/analysis/analyzerPositionCoreR142';
import { inspectPlaystyleActivationR124 } from './efootball2027PhaseCatalogR124';
export const AUTONOMOUS_CARD_R417_VERSION='40.80-r417-autonomous-card-v1' as const,POSITION_USAGE_R416_VERSION='40.80-r416-universal-position-usage-v1' as const;
const FIELD:PositionCode[]=['CF','SS','LWF','RWF','LMF','RMF','AMF','CMF','DMF','CB','LB','RB'],ALL=[...FIELD,'GK' as PositionCode];
type Fit='ACTIVE'|'PARTIAL'|'INACTIVE'|'UNKNOWN';type Role={position:PositionCode;score:number;dnaScore:number;proficiency:PositionProficiencyLevel;styleFit:Fit;eligible:boolean;offensiveStyleStatus:string;defensiveStyleStatus:string};
const good=(s:string)=>s==='LIKELY_ACTIVE'||s==='UNVERIFIED_POSITION',bad=(s:string)=>s==='LIKELY_INACTIVE'||s==='CHECK_POSITION';
function style(a:string,d:string):Fit{return bad(a)&&bad(d)?'INACTIVE':good(a)&&good(d)?'ACTIVE':good(a)||good(d)||bad(a)||bad(d)?'PARTIAL':'UNKNOWN'}
function role(p:ParsedCard,x:PositionCode,a:ReturnType<typeof fillAttributes>,skills:string[]):Role{const pr=x===p.mainPosition?'HIGH':p.positionProficiencies?.[x]??'UNKNOWN',listed=(p.positions??[]).includes(x),eligible=x===p.mainPosition||pr==='HIGH'||pr==='INTERMEDIATE'||listed,o=inspectPlaystyleActivationR124(p.offensivePlaystyle??p.playstyle??null,'OFFENSIVE',x),d=inspectPlaystyleActivationR124(p.defensivePlaystyle??null,'DEFENSIVE',x),sf=style(o.status,d.status),dna=positionScore(x,a,skills,{}),bonus=x===p.mainPosition?3:pr==='HIGH'?4:pr==='INTERMEDIATE'?-1:listed?-5:-18,styleBonus=sf==='ACTIVE'?3.5:sf==='PARTIAL'?1:sf==='INACTIVE'?-3.5:0;return{position:x,score:Math.round(Math.max(1,Math.min(100,dna+bonus+styleBonus))*10)/10,dnaScore:Math.round(dna*10)/10,proficiency:pr,styleFit:sf,eligible,offensiveStyleStatus:o.status,defensiveStyleStatus:d.status}}
export function rankAutonomousRolesR417(p:ParsedCard){if(p.mainPosition==='GK')return{primary:'GK' as PositionCode,topPositions:['GK'] as PositionCode[],entries:[] as Role[]};const a=fillAttributes(p),skills=[...(p.nativeSkills??[]),...(p.additionalSkills??[]),...(p.specialSkills??[])],entries=FIELD.map(x=>role(p,x,a,skills)).filter(x=>x.eligible).sort((x,y)=>y.score-x.score||y.dnaScore-x.dnaScore),top=entries.slice(0,3);return{primary:top[0]?.position??p.mainPosition,topPositions:top.map(x=>x.position),entries}}
export function buildPositionUsageR416(result:AnalysisResult):PositionUsageR416Analysis{const p=result.parsed,gk=p.mainPosition==='GK',rank=rankAutonomousRolesR417(p),a=fillAttributes(p),skills=[...(p.nativeSkills??[]),...(p.additionalSkills??[]),...(p.specialSkills??[])],by=new Map(rank.entries.map(x=>[x.position,x]));const entries=ALL.map((x):PositionUsageR416Entry=>{if(gk||x==='GK'){const ok=gk&&x==='GK';return{position:x,label:POSITION_PT[x],rating:Number.isFinite(Number(p.positionRatings[x]))?Number(p.positionRatings[x]):null,proficiency:ok?'HIGH':'LOW',proficiencyState:ok?'NATURAL':'BLOCKED',offensiveStyleStatus:'UNKNOWN',defensiveStyleStatus:'UNKNOWN',styleFit:ok?'ACTIVE':'UNKNOWN',recommended:ok,fitScore:ok?100:0,reason:ok?'GOL fixo em GOL.':'GOL não entra na adaptação.'}}const r=by.get(x)??role(p,x,a,skills),natural=x===p.mainPosition,state:PositionUsageR416Entry['proficiencyState']=natural?'NATURAL':r.proficiency==='HIGH'?'READY':r.proficiency==='INTERMEDIATE'?'POSITION_TRAINING':r.proficiency==='LOW'?'LOW':'REVIEW',rating=Number(p.positionRatings[x]);return{position:x,label:POSITION_PT[x],rating:Number.isFinite(rating)?rating:null,proficiency:r.proficiency,proficiencyState:state,offensiveStyleStatus:r.offensiveStyleStatus,defensiveStyleStatus:r.defensiveStyleStatus,styleFit:r.styleFit,recommended:rank.topPositions.includes(x),fitScore:r.score,reason:r.styleFit==='INACTIVE'?'Estilo inativo; DNA ainda pode favorecer esta função.':state==='POSITION_TRAINING'?'Alvo de Treino de Posição.':'Avaliação por DNA, sem GER.'}});return{version:POSITION_USAGE_R416_VERSION,canonicalBuildLocked:true,sameBuildAcrossFieldPositions:true,goalkeeperLocked:gk,naturalPosition:p.mainPosition,entries,recommendedPositions:rank.topPositions,automaticPrimaryPosition:rank.primary,automaticTopPositions:rank.topPositions,warnings:[gk?'GOL exclusivo.':'Top 3 automático por DNA com uma única ficha.','Nota e proficiência são independentes; GER não decide.','Estilo inativo penaliza, mas não bloqueia.']}}
export function applyPositionUsageR416(result:AnalysisResult):AnalysisResult{return{...result,positionUsageR416:buildPositionUsageR416(result)}}
export function applyAutonomousRoleSeedR417(result:AnalysisResult):AnalysisResult{const r=rankAutonomousRolesR417(result.parsed),e=r.entries.find(x=>x.position===r.primary);return{...result,bestPosition:{code:r.primary,label:POSITION_PT[r.primary],score:e?.score??result.bestPosition.score}}}
