import type { OcrZone } from './ocrZonesModelR164';
import { buildPrintQualityReport, type PrintQualityReport } from './validation';
export { DEFAULT_OCR_ZONES } from './ocrZonesModelR164';
export type { OcrZone, OcrZoneKey } from './ocrZonesModelR164';

export async function inspectPrintQuality(file:File|Blob):Promise<PrintQualityReport|null>{
 if(typeof document==='undefined'||typeof createImageBitmap==='undefined')return null;const bitmap=await createImageBitmap(file).catch(()=>null);if(!bitmap)return null;const width=bitmap.width,height=bitmap.height,canvas=document.createElement('canvas');
 try{const sampleWidth=Math.min(420,Math.max(240,width)),scale=sampleWidth/Math.max(1,width);canvas.width=sampleWidth;canvas.height=Math.max(1,Math.round(height*scale));const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)return null;ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const data=ctx.getImageData(0,0,canvas.width,canvas.height).data,total=Math.max(1,canvas.width*canvas.height),gray=new Float32Array(total);let sum=0,sumSq=0,darkPixels=0,lightPixels=0,glarePixels=0;
  for(let i=0,p=0;i<data.length;i+=4,p++){const r=data[i],g=data[i+1],b=data[i+2],v=r*.299+g*.587+b*.114,s=Math.max(r,g,b)-Math.min(r,g,b);gray[p]=v;sum+=v;sumSq+=v*v;if(v<=10)darkPixels++;if(v>=245)lightPixels++;if(v>=238&&s<=18)glarePixels++;}
  let edgeSum=0,edgeCount=0,lapSum=0,lapSumSq=0,fineEdges=0,hb=0,hi=0,hbc=0,hic=0,vb=0,vi=0,vbc=0,vic=0;
  for(let y=1;y<canvas.height-1;y++)for(let x=1;x<canvas.width-1;x++){const p=y*canvas.width+x,gx=Math.abs(gray[p+1]-gray[p-1]),gy=Math.abs(gray[p+canvas.width]-gray[p-canvas.width]),edge=gx+gy,lap=gray[p-1]+gray[p+1]+gray[p-canvas.width]+gray[p+canvas.width]-gray[p]*4;edgeSum+=edge;edgeCount++;if(edge>28)fineEdges++;lapSum+=lap;lapSumSq+=lap*lap;const dx=Math.abs(gray[p]-gray[p-1]);if(x%8===0){vb+=dx;vbc++;}else{vi+=dx;vic++;}const dy=Math.abs(gray[p]-gray[p-canvas.width]);if(y%8===0){hb+=dy;hbc++;}else{hi+=dy;hic++;}}
  const brightness=sum/total,contrast=Math.sqrt(Math.max(0,sumSq/total-brightness*brightness)),sharpness=edgeSum/Math.max(1,edgeCount),lapMean=lapSum/Math.max(1,edgeCount),laplacianVariance=Math.max(0,lapSumSq/Math.max(1,edgeCount)-lapMean*lapMean),blockiness=Math.max(0,((vb/Math.max(1,vbc)-vi/Math.max(1,vic))+(hb/Math.max(1,hbc)-hi/Math.max(1,hic)))/2);
  return buildPrintQualityReport({width,height,sharpness:+sharpness.toFixed(1),brightness:+brightness.toFixed(1),contrast:+contrast.toFixed(1),laplacianVariance:+laplacianVariance.toFixed(1),darkClipRatio:+(darkPixels/total).toFixed(4),lightClipRatio:+(lightPixels/total).toFixed(4),glareRatio:+(glarePixels/total).toFixed(4),blockiness:+blockiness.toFixed(1),textEdgeDensity:+(fineEdges/Math.max(1,edgeCount)).toFixed(4)});
 }finally{bitmap.close?.();canvas.width=1;canvas.height=1;}
}

export async function createZoneOriginPreview(file:File|Blob,zone:OcrZone):Promise<string|null>{
 const isAndroid=typeof navigator!=='undefined'&&/Android/i.test(navigator.userAgent);if(isAndroid)return null;if(typeof document==='undefined'||typeof createImageBitmap==='undefined')return null;const bitmap=await createImageBitmap(file).catch(()=>null);if(!bitmap)return null;const canvas=document.createElement('canvas');
 try{const cropX=Math.max(0,Math.round(bitmap.width*zone.x)),cropY=Math.max(0,Math.round(bitmap.height*zone.y)),cropW=Math.max(1,Math.round(bitmap.width*zone.w)),cropH=Math.max(1,Math.round(bitmap.height*zone.h)),targetWidth=Math.min(900,Math.max(320,cropW)),scale=targetWidth/cropW;canvas.width=Math.round(cropW*scale);canvas.height=Math.round(cropH*scale);const ctx=canvas.getContext('2d');if(!ctx)return null;ctx.drawImage(bitmap,cropX,cropY,cropW,cropH,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.9);}finally{bitmap.close?.();canvas.width=1;canvas.height=1;}
}

export type LocalEnhancementMode='adaptive'|'contrast'|'sharp'|'color'|'binary'|'inverted';
export async function enhanceImageLocally(file:File|Blob,mode:LocalEnhancementMode='adaptive'):Promise<Blob|File>{
 if(typeof document==='undefined'||typeof createImageBitmap==='undefined')return file;const bitmap=await createImageBitmap(file).catch(()=>null);if(!bitmap)return file;const canvas=document.createElement('canvas');
 try{const maxDimension = 1600; const scale = Math.min(1, maxDimension / Math.max(1, Math.max(bitmap.width, bitmap.height)));canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)return file;ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const image=ctx.getImageData(0,0,canvas.width,canvas.height),data=image.data;let sum=0;for(let i=0;i<data.length;i+=4)sum+=data[i]*.299+data[i+1]*.587+data[i+2]*.114;const mean=sum/Math.max(1,data.length/4),contrast=mode==='contrast'?1.7:mode==='sharp'?1.45:mode==='color'?1.22:1.35,lift=Math.max(-22,Math.min(28,132-mean));
  if(mode==='binary'||mode==='inverted'){const grays=new Uint8Array(data.length/4);let gs=0;for(let i=0,p=0;i<data.length;i+=4,p++){const g=Math.round(data[i]*.299+data[i+1]*.587+data[i+2]*.114);grays[p]=g;gs+=g;}const threshold=Math.max(72,Math.min(190,Math.round(gs/Math.max(1,grays.length))));for(let i=0,p=0;i<data.length;i+=4,p++){const dark=grays[p]<=threshold,v=mode==='inverted'?(dark?255:0):(dark?0:255);data[i]=data[i+1]=data[i+2]=v;}}
  else for(let i=0;i<data.length;i+=4){const gray=data[i]*.299+data[i+1]*.587+data[i+2]*.114;for(let c=0;c<3;c++){const sat=mode==='color'?1.18:1,v=(gray+(data[i+c]-gray)*sat-128)*contrast+128+lift;data[i+c]=Math.max(0,Math.min(255,v));}}
  ctx.putImageData(image,0,0);if(mode==='sharp'||mode==='adaptive'){ctx.globalAlpha=mode==='sharp'?.42:.22;ctx.filter='contrast(1.25) saturate(0.88)';ctx.drawImage(canvas,0,0);ctx.globalAlpha=1;ctx.filter='none';}return await new Promise<Blob|File>(resolve=>canvas.toBlob(blob=>resolve(blob??file),'image/png',.96));
 }finally{bitmap.close?.();canvas.width=1;canvas.height=1;}
}
