import assert from 'node:assert/strict';
const store = new Map<string,string>();
(globalThis as unknown as {window:unknown}).window={localStorage:{getItem:(key:string)=>store.get(key)??null,setItem:(key:string,value:string)=>{store.set(key,value)},removeItem:(key:string)=>{store.delete(key)},key:(index:number)=>Array.from(store.keys())[index]??null,get length(){return store.size}}};
const community=require('../src/modules/community/communitySharing.ts') as typeof import('../src/modules/community/communitySharing');
const commercial=require('../src/modules/commercial/commercialization.ts') as typeof import('../src/modules/commercial/commercialization');
assert.equal(community.COMMUNITY_SHARING_VERSION,'29.80.0');
const pkg=community.createCommunitySharePackage({kind:'player_build',title:'Ficha segura',visibility:'private',payload:{player:'Teste',token:'remover',nested:{password:'remover',points:62}},expiresInDays:7});
assert.ok(pkg.code.startsWith('BM-'));
assert.equal(community.verifyCommunitySharePackage(pkg).valid,true);
assert.equal(JSON.stringify(pkg).includes('remover'),false,'Segredos não podem entrar no pacote');
assert.equal(community.verifyCommunitySharePackage({...pkg,title:'alterada'}).valid,false,'Adulteração deve ser bloqueada');
const review=community.queueCommunityImport(pkg); assert.equal(review.status,'review');
const accepted=community.decideCommunityImport(review.id,true); assert.equal(accepted.packages.length,1);
assert.equal(commercial.COMMERCIALIZATION_VERSION,'29.80.0');
assert.equal(commercial.COMMERCIAL_PLANS.essential.priceLabel,'Preço definido pelo administrador');
const trial=commercial.beginCommercialTrial('pro',7); assert.equal(trial.license?.status,'trial');
const rights=commercial.resolveCommercialEntitlements(null,trial); assert.equal(rights.features.community_publish,true); assert.equal(rights.limits.devices,2);
const lgpd=commercial.createLgpdRequest('export','Quero meus dados'); assert.equal(lgpd.lgpdRequests[0].type,'export');
const exported=commercial.createCommercialDataExport(); assert.match(exported.notice,/não processa pagamentos/i);
console.log('✓ v29.80 community + commercialization regression passed');
