import assert from 'node:assert/strict';
import { analyzeCard, type PositionCode } from '@/lib/analyzer';
import { buildFormationLineup, getFormationBlueprint } from '@/lib/formationRoleEngine';
import { TACTICAL_STUDIO_2_VERSION, createDefaultTacticalSequence, duplicateSequenceFrame, exportTacticalSequence, removeSequenceFrame, updateSequencePlayer, validateTacticalSequence } from '@/modules/tactical-studio/tacticalStudio2Engine';
import { OPPONENT_ASSISTANT_VERSION, buildOpponentMatchAssistant } from '@/modules/opponents/opponentMatchAssistant';
const specs:Array<[string,PositionCode,string]>=[['Goleiro','GK','Goleiro defensivo'],['Lateral Direito','RB','Lateral defensivo'],['Zagueiro 1','CB','Destruidor'],['Zagueiro 2','CB','Defensor criativo'],['Lateral Esquerdo','LB','Lateral defensivo'],['Volante','DMF','1º Volante'],['Meia','CMF','Meia versátil'],['Armador','AMF','Armador criativo'],['Ponta Direita','RWF','Ala Produtivo'],['Centroavante','CF','Artilheiro'],['Ponta Esquerda','LWF','Ala Produtivo']];
const results=specs.map(([name,position,style],index)=>analyzeCard(`[AJUSTES MANUAIS]\nCONFIRMAÇÃO MANUAL: SIM\nNOME DO JOGADOR: ${name}\nPOSIÇÃO PRINCIPAL: ${position}\nESTILO DE JOGO: ${style}\nPONTOS TOTAIS: 60\nTalento ofensivo: ${78+index}\nControle de bola: ${80+index}\nPasse rasteiro: ${78+index}\nPasse alto: ${76+index}\nFinalização: ${74+index}\nVelocidade: ${79+index}\nAceleração: ${78+index}\nTalento defensivo: ${82-index}\nDesarme: ${81-index}\nContato físico: 82\nResistência: 84\n[FIM AJUSTES]`,position==='GK'?'GOALKEEPER':'COMPETITIVE',position,`v2950-${index}.png`,{formation:'4-3-3',style:'POSSE_DE_BOLA'}));
const formation=getFormationBlueprint('4-3-3');const lineup=buildFormationLineup(results,formation);const sequence=createDefaultTacticalSequence(formation,lineup,'POSSE_DE_BOLA');
assert.equal(TACTICAL_STUDIO_2_VERSION,'29.50.0');assert.ok(sequence.frames.length>=4);assert.ok(sequence.frames.every(frame=>frame.players.length===formation.slots.length));assert.ok(sequence.frames.every(frame=>frame.actions.length>=3));assert.equal(validateTacticalSequence(sequence).valid,true);
const moved=updateSequencePlayer(sequence,sequence.frames[0].id,sequence.frames[0].players[0].slotId,120,-20);assert.ok(moved.frames[0].players[0].x<=98&&moved.frames[0].players[0].y>=2);
const duplicated=duplicateSequenceFrame(moved,moved.frames[0].id);assert.equal(duplicated.frames.length,moved.frames.length+1);const removed=removeSequenceFrame(duplicated,duplicated.frames[1].id);assert.equal(removed.frames.length,moved.frames.length);assert.equal(JSON.parse(exportTacticalSequence(removed)).appVersion,'29.50.0');
assert.equal(OPPONENT_ASSISTANT_VERSION,'29.50.0');for(const [state,minute,expected] of [['pre-match',0,'A'],['drawing',75,'B'],['losing',45,'B'],['winning',70,'C']] as const){const report=buildOpponentMatchAssistant(results,'4-3-3','POSSE_DE_BOLA',{profile:'CONTRA_RAPIDO',formation:'4-2-3-1',strength:'VELOCIDADE'},state,minute);assert.ok(report);assert.equal(report!.plans.length,3);assert.deepEqual(report!.plans.map(plan=>plan.id),['A','B','C']);assert.equal(report!.activePlan,expected);assert.ok(report!.plans.every(plan=>plan.instructions.length>=3&&plan.marking.length>=3));assert.ok(report!.locks.some(item=>item.includes('automaticamente')));}
console.log('v29.50 tactical studio 2 + opponent assistant: OK');
