import assert from 'node:assert/strict';
import { buildBuildOutcomeCalibrationR460 } from '../src/modules/matches/buildOutcomeCalibrationR460';
import { buildGenerationSignatureR464, cardFingerprint, type MatchValidationRecord } from '../src/lib/appEvolution';
const result:any={parsed:{playerName:'R468',mainPosition:'CMF',nativeSkills:[],specialSkills:[],additionalSkills:[],attributes:{}},training:{passing:4},buildName:'A',recommendedSkills:[],recommendedImpetos:[],tacticalProfile:{formation:'4-2-2-2',style:'POSSE_DE_BOLA'},usageFunctionR457:'Orquestrador'};
const fingerprint=cardFingerprint(result); const gen=buildGenerationSignatureR464(result); const snap:any={version:'40.80-r460-build-outcome-snapshot-v1',engineRevision:'R459',usageFunction:'Orquestrador',tacticalStyle:'POSSE_DE_BOLA',formation:'4-2-2-2',actions:[{id:'short_creation',label:'Passe',demand:90,projectedGain:3,projectedScore:85,decisionConfidence:95}]};
const rec=(id:string,observed:boolean):MatchValidationRecord=>({id,cardFingerprint:fingerprint,playerName:'R468',targetPosition:'CMF',formation:'4-2-2-2',teamStyle:'POSSE_DE_BOLA',buildName:'A',buildSignature:'b',playedAt:`2026-09-${id.slice(-2)}T12:00:00Z`,minutes:90,overallRating:3,passing:3,movement:3,finishing:3,defending:3,physical:3,stamina:3,tags:[],note:'',usageFunction:'Orquestrador',connection:'stable',inputDelayRating:1,sessionIdR462:id,buildGenerationSignatureR464:gen,gameplayImpactSnapshotR460:snap,metrics:{keyPasses:0,progressivePasses:0,passErrors:0},observedMetricKeysR468:observed?['keyPasses','progressivePasses','passErrors']:[]} as any);
const seen=buildBuildOutcomeCalibrationR460(result,[rec('o01',true),rec('o03',true),rec('o05',true)]); const unseen=buildBuildOutcomeCalibrationR460(result,[rec('u01',false),rec('u03',false),rec('u05',false)]);
const a=seen.actions.find(x=>x.id==='short_creation')!, b=unseen.actions.find(x=>x.id==='short_creation')!; assert.ok(a.observedScore < b.observedScore); assert.equal(Math.round(b.observedScore),50);
console.log(`R468 aprovado: zero observado ${a.observedScore} != zero ausente ${b.observedScore}.`);
