import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createProductionAnalysisR138 } from '../src/modules/analysis/productionOrchestratorR138';
const source=fs.readFileSync('src/lib/cleanSlatePerformance2027V4080R119.ts','utf8');
assert.doesNotMatch(source,/activeMatchCalibration\(input\)\?\.status!==['"]ACTIVE['"]/,'R136 não pode desligar Pareto/certificação.');
assert.match(source,/function certifyExactTrainingR457/);
assert.match(source,/function optimisticUpperBoundR457/);
assert.match(source,/EXACT_TRAINING_CACHE_R457/);
assert.match(source,/status:'PROVEN_GLOBAL'/);
const raw=`[AJUSTES MANUAIS]\nCONFIRMAÇÃO MANUAL: SIM\nNOME DO JOGADOR: Certificação R457\nPOSIÇÃO PRINCIPAL: CMF\nESTILO DE JOGO: Orquestrador\nPONTOS TOTAIS: 8\nControle de bola: 84\nDrible: 80\nCondução firme: 82\nPasse rasteiro: 88\nPasse alto: 86\nTalento ofensivo: 78\nFinalização: 72\nVelocidade: 80\nAceleração: 82\nEquilíbrio: 82\nResistência: 88\nTalento defensivo: 76\nDedicação defensiva: 78\nDesarme: 75\nAgressividade: 73\n[FIM AJUSTES]`;
const request={rawText:raw,targetPosition:'CMF',objective:'COMPETITIVE' as const,tacticalProfile:{formation:'AUTO',style:'POSSE_DE_BOLA'} as any};
const first:any=createProductionAnalysisR138(request);
const second:any=createProductionAnalysisR138(request);
const certificate=first.cleanSlate2027R119?.optimalityCertificateR457;
assert.equal(certificate?.version,'40.80-r457-exact-training-v2');
assert.equal(certificate?.status,'PROVEN_GLOBAL');
assert.ok(Number(certificate?.exactStatesEvaluated)>0);
assert.ok(Number(certificate?.upperBoundChecks)>0);
assert.ok(Number(certificate?.prunedBranches)>=0);
assert.equal(certificate?.cacheHit,false);
assert.equal(first.trainingPointsUsed,8);
assert.equal(first.cleanSlate2027R119?.guards?.exactBudget,true);
assert.deepEqual(second.training,first.training,'A mesma evidência deve reutilizar a certificação sem mudar a ficha.');
assert.equal(second.cleanSlate2027R119?.optimalityCertificateR457?.cacheHit,true,'Reanálise idêntica deve usar o cache exato R457.');
console.log(`R457 Stage 4 aprovada: ótimo global certificado em ${certificate.exactStatesEvaluated} estados finais; branch-and-bound seguro + cache LRU preservam a ficha.`);
