import type { AnalysisResult, TacticalFormation, TacticalStyle } from '@/lib/analyzer';
import { buildAdvancedOpponentReport } from '@/lib/opponentAdvanced';
import { buildOpponentAnalysisReport, type OpponentAnalysisInput } from '@/lib/opponentAnalysis';
import { buildEliteTeamReport } from '@/lib/teamOptimizer';

export const OPPONENT_ASSISTANT_VERSION = '29.50.0';
export type LiveMatchState = 'pre-match' | 'winning' | 'drawing' | 'losing';
export type OpponentPlanId = 'A' | 'B' | 'C';
export type OpponentPlan = { id: OpponentPlanId; title: string; purpose: string; formation: TacticalFormation; style: TacticalStyle; risk: 'baixo' | 'moderado' | 'alto'; instructions: string[]; marking: string[]; substitutions: string[]; triggers: string[] };
export type OpponentMatchAssistantReport = { confidence: number; headline: string; preMatchChecklist: string[]; first15Minutes: string[]; halftimeQuestions: string[]; plans: OpponentPlan[]; activePlan: OpponentPlanId; liveInstructions: string[]; postMatchQuestions: string[]; locks: string[] };

const playerName = (result: AnalysisResult | undefined, fallback: string) => result?.parsed.playerName?.trim() || fallback;
const firstByPositions = (results: AnalysisResult[], positions: string[]) => results.find((item) => positions.includes(item.bestPosition.code));
const styleForPlan = (base: TacticalStyle, plan: OpponentPlanId): TacticalStyle => plan === 'A' ? (base === 'AUTO' ? 'POSSE_DE_BOLA' : base) : plan === 'B' ? 'CONTRA_ATAQUE_RAPIDO' : 'CONTRA_ATAQUE';
const activePlanForState = (state: LiveMatchState, minute: number): OpponentPlanId => state === 'losing' || (state === 'drawing' && minute >= 70) ? 'B' : state === 'winning' && minute >= 60 ? 'C' : 'A';

export function buildOpponentMatchAssistant(results: AnalysisResult[], ownFormation: TacticalFormation, ownStyle: TacticalStyle, input: OpponentAnalysisInput, state: LiveMatchState, minute: number): OpponentMatchAssistantReport | null {
  const base = buildOpponentAnalysisReport(results, ownFormation, ownStyle, input);
  const advanced = buildAdvancedOpponentReport(results, ownFormation, ownStyle, input);
  const elite = buildEliteTeamReport(results, ownFormation, ownStyle);
  if (!base || !advanced || !elite) return null;
  const selected = elite.lineup.map((pick) => results.find((item) => item.parsed.playerName === pick.playerName)).filter((item): item is AnalysisResult => Boolean(item));
  const defensiveMid = firstByPositions(selected, ['DMF', 'CMF']); const creator = firstByPositions(selected, ['AMF', 'CMF', 'SS']);
  const striker = firstByPositions(selected, ['CF', 'SS']); const defender = firstByPositions(selected, ['CB', 'LB', 'RB']);
  const fastPlayer = [...selected].sort((a, b) => Number(b.teamMap?.sectorScores?.aceleracao ?? 0) - Number(a.teamMap?.sectorScores?.aceleracao ?? 0))[0];
  const planA: OpponentPlan = { id:'A', title:'Plano A — controlar e confirmar', purpose:'Começar sem abrir o time e validar se o rival realmente joga como o perfil informado.', formation:ownFormation, style:styleForPlan(ownStyle,'A'), risk:'baixo', instructions:[base.adjustments[0]?.action || 'Proteja primeiro a principal ameaça.','Faça a bola circular antes de acelerar.',`Explore: ${advanced.bestOpportunity}`], marking:[`${playerName(defensiveMid,'Volante')} protege a zona central.`,`${playerName(defender,'Defensor de cobertura')} não abandona a profundidade.`,'Marcação individual somente no organizador ou finalizador mais perigoso.'], substitutions:['Sem troca programada antes dos 55 minutos, salvo lesão ou queda física clara.',`Se faltar criação, aproxime ${playerName(creator,'o meia criador')} da área.`], triggers:['Adversário confirma o perfil previsto.','Sua saída encontra pelo menos duas opções.','Nenhuma perda recorrente no corredor central.'] };
  const planB: OpponentPlan = { id:'B', title:'Plano B — buscar o resultado', purpose:'Aumentar presença ofensiva sem perder completamente a proteção da transição.', formation:base.recommendedFormation, style:styleForPlan(ownStyle,'B'), risk:'alto', instructions:['Acelere depois de atrair a primeira pressão.','Ataque a fraqueza principal com dois jogadores, não com avanço isolado.',`Use ${playerName(fastPlayer,'o jogador mais rápido')} para atacar profundidade.`], marking:[`${playerName(defensiveMid,'O volante')} permanece como proteção fixa.`,'Um lateral sobe por vez.','Pressão forte após domínio ruim, passe recuado ou recepção de costas.'], substitutions:[`Entre 55–70 min: entrada de velocidade/criação para apoiar ${playerName(striker,'o atacante')}.`,'Após 75 min perdendo: retirar o jogador de menor impacto ofensivo, preservando um volante.'], triggers:['Perdendo no placar.','Empate após 70 minutos.','Rival recuou e entregou território.'] };
  const planC: OpponentPlan = { id:'C', title:'Plano C — proteger a vantagem', purpose:'Reduzir espaços perigosos e manter uma saída para o rival não pressionar sem risco.', formation:ownFormation.startsWith('3-') ? ownFormation : ('4-2-3-1' as TacticalFormation), style:styleForPlan(ownStyle,'C'), risk:'moderado', instructions:['Bloco médio compacto; não recuar até dentro da área cedo demais.','Circular após recuperar em vez de devolver a bola imediatamente.','Atacar o espaço deixado pelo rival com poucos jogadores.'], marking:[`${playerName(defensiveMid,'Primeiro volante')} protege a frente da zaga.`,`${playerName(defender,'Zagueiro de cobertura')} controla a profundidade.`,'Fechar cruzador antes de lotar a área.'], substitutions:['Entre 60–75 min: renovar meio-campo e corredor mais atacado.','Últimos 10 min: troca apenas se melhorar cobertura, passe seguro ou retenção.'], triggers:['Vencendo após 60 minutos.','Rival passou a usar bolas diretas.','Seus jogadores ofensivos perderam capacidade de pressionar.'] };
  const plans=[planA,planB,planC]; const activePlan=activePlanForState(state,minute); const active=plans.find((plan)=>plan.id===activePlan)||planA;
  const confidence=Math.max(35,Math.min(98,Math.round((base.matchupScore+advanced.overallSectorEdge+advanced.duelEdge)/3)));
  return { confidence, headline:`${active.title} recomendado aos ${Math.max(0,Math.min(120,minute))} minutos. ${base.verdict}`, preMatchChecklist:['Confirmar formação e estilo após os primeiros ataques.','Identificar organizador, finalizador e corredor preferido.','Testar uma saída curta e uma saída direta.','Não aplicar mudanças automáticas; confirme no campo.'], first15Minutes:['Não pressionar de forma contínua sem gatilho.',`Observe se a ameaça principal é realmente: ${base.mainThreats[0]||'não confirmada'}.`,`Teste a oportunidade: ${advanced.bestOpportunity}.`], halftimeQuestions:['De onde vieram as chances mais perigosas?','Qual jogador rival recebe livre?','Seu Plano A criou saída e finalização?','A conexão permite passe rápido ou exige jogo mais seguro?'], plans, activePlan, liveInstructions:active.instructions, postMatchQuestions:['O perfil previsto correspondeu ao jogo real?','Qual ajuste reduziu mais o risco?','Qual substituição mudou o desempenho?','Salvar o plano como referência ou descartá-lo?'], locks:['Nenhuma escalação é alterada automaticamente.','As marcações são recomendações e exigem confirmação.','Se o adversário mudar, reavalie o plano antes de trocar vários jogadores.'] };
}
