import type { MatchRecordingDescriptor, MatchRecordingQuality } from './recorder-stub';
export type MatchPhase = 'build-up'|'attack'|'defensive-transition'|'defense'|'set-piece'|'game-management'|'unknown';
export type MatchSeverity = 'positive'|'low'|'medium'|'high'|'critical';
export type MatchEventKind = 'pass-error'|'dangerous-turnover'|'marking-error'|'cursor-error'|'forced-shot'|'defender-out-of-line'|'late-recomposition'|'pressing-error'|'game-management'|'good-transition'|'good-build-up'|'good-play'|'possible-delay'|'critical-moment'|'goal-for'|'goal-against'|'note';
export type MatchEventMarker = {id:string;atMs:number;kind:MatchEventKind;source:'manual'|'automatic';confidence:number;title:string;detail:string;playerId?:string|null;phase?:MatchPhase;severity?:MatchSeverity;reviewStatus?:'suggested'|'confirmed'|'rejected';observed?:string;why?:string;consequence?:string;betterDecision?:string;correction?:string;clipStartMs?:number;clipEndMs?:number;relatedMarkerId?:string|null};
export type MatchTrainerSession = {id:string;createdAt:string;updatedAt:string;title:string;source:'native-recording'|'imported-video';videoPath?:string;fileName:string;fileSizeBytes:number;recording?:MatchRecordingDescriptor|null;quality:MatchRecordingQuality|'imported';formation:string;teamStyle:string;manager:string;connectionRating:1|2|3|4|5;notes:string;analysis?:{qualityScore:number;confidence?:'low'|'medium'|'high';automaticMarkers:MatchEventMarker[]}|null;markers:MatchEventMarker[];dismissedAutomaticMarkerIds?:string[];status:'recorded'|'analyzing'|'review'|'completed'|'failed'};
export const MATCH_EVENT_CATALOG:Array<{kind:MatchEventKind;label:string;shortLabel:string;group:string;phase:MatchPhase;severity:MatchSeverity}>=[];
export function analyzeMatchVideo(_source:Blob|string,_options:Record<string,unknown>):Promise<any>{return Promise.resolve({})}
export function createMatchMarker(kind:MatchEventKind,atMs:number,detail='',source:'manual'|'automatic'='manual',confidence=100,overrides:Partial<MatchEventMarker>={}){return {id:'x',kind,atMs,detail,source,confidence,title:kind,...overrides} as MatchEventMarker}
export function createMatchTrainerSession(_input:Record<string,unknown>):MatchTrainerSession{throw new Error('stub')}
export function deleteMatchTrainerSession(_id:string):MatchTrainerSession[]{return []}
export function exportMatchTrainerReport(_session:MatchTrainerSession):string{return ''}
export function readMatchTrainerSessions():MatchTrainerSession[]{return []}
export function getVisibleMatchMarkers(session:MatchTrainerSession):MatchEventMarker[]{return session.markers}
export function getConfirmedMatchMarkers(session:MatchTrainerSession):MatchEventMarker[]{return session.markers}
export function isAttackEvent(_kind:MatchEventKind):boolean{return true}
export function isDefenseEvent(_kind:MatchEventKind):boolean{return true}
export function summarizeMatchTrainerSession(_session:MatchTrainerSession){return {verdict:'',overallScore:null as number|null,confidenceScore:0,confirmedMarkers:0,candidateMoments:0,passErrors:0,dangerousTurnovers:0,markingErrors:0,cursorErrors:0,forcedShots:0,possibleDelay:0,goodPlays:0,priorities:[] as string[],matchRules:[] as string[],areas:[] as Array<{id:string;label:string;score:number|null;evidenceCount:number;diagnosis:string;tone:string}>,topProblems:[] as Array<{kind:MatchEventKind;title:string;occurrences:number;impact:number;severity:MatchSeverity;moments:number[];observed:string;why:string;consequence:string;betterDecision:string;correction:string}>,strengths:[] as string[],trainingPlan:[] as Array<{id:string;title:string;linkedKind:MatchEventKind;objective:string;rule:string;repetitions:string;successCriteria:string;estimatedMinutes:number;priority:MatchSeverity}>,tacticalDiagnosis:{configuredShape:'',configuredStyle:'',structure:'',styleFit:'',gameManagement:'',connectionGuardrail:'',recommendations:[] as string[]}}}
export function buildMatchTrainerEvolution(_sessions:MatchTrainerSession[],_activeId?:string|null){return {sessionsAnalyzed:0,currentScore:null as number|null,previousScore:null as number|null,scoreDelta:null as number|null,trend:'',recurringProblem:'',improvements:[] as string[],warnings:[] as string[],metrics:[] as Array<{id:string;label:string;current:number|null;previous:number|null;delta:number|null;unit:string;direction:string}>}}
export function upsertMatchTrainerSession(session:MatchTrainerSession):MatchTrainerSession[]{return [session]}
