'use client';
import { CheckCircle2, Clock3, Download, Loader2, ShieldCheck, Smartphone } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { ApkDownloadProgress } from '@/lib/secureStorage';
function clamp(value:number,min=0,max=100){return Math.max(min,Math.min(max,Number.isFinite(value)?value:0))}
export function formatProgressBytes(value?:number){const bytes=Math.max(0,Number(value||0));if(bytes<1024)return `${Math.round(bytes)} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(bytes>=100*1024?0:1)} KB`;return `${(bytes/(1024*1024)).toFixed(bytes>=10*1024*1024?1:2)} MB`}
export function formatRemainingTime(seconds?:number|null){if(!seconds||!Number.isFinite(seconds)||seconds<=0)return '';if(seconds<10)return 'menos de 10 s';if(seconds<60)return `cerca de ${Math.ceil(seconds/5)*5} s`;const minutes=Math.ceil(seconds/60);if(minutes<60)return `cerca de ${minutes} min`;const hours=Math.floor(minutes/60),rest=minutes%60;return rest?`cerca de ${hours} h ${rest} min`:`cerca de ${hours} h`}
function formatActivityDuration(seconds:number){const safe=Math.max(0,Math.floor(seconds));if(safe<60)return `${safe}s`;const m=Math.floor(safe/60),s=safe%60;return s?`${m}min ${s}s`:`${m}min`}
export function updateOverallPercent(progress:ApkDownloadProgress|null){if(!progress)return 0;const transfer=clamp(progress.percent);switch(progress.phase){case'refreshing-manifest':return 1;case'preparing-backup':return 3;case'awaiting-permission':return 4;case'connecting':return 5;case'downloading':case'downloading-system':case'downloading-http':return Math.round(5+transfer*.75);case'copying':return Math.round(80+transfer*.08);case'verifying':return 92;case'opening-installer':return 97;case'ready':return 98;default:return transfer}}
export function updateStageLabel(progress:ApkDownloadProgress|null){if(!progress)return'Preparando atualização';switch(progress.phase){case'refreshing-manifest':return'Conferindo versão publicada';case'preparing-backup':return'Protegendo seus dados';case'awaiting-permission':return'Aguardando permissão do Android';case'connecting':return'Conectando ao servidor';case'downloading-system':return'Baixando pelo Android';case'downloading-http':return'Baixando pela rota reserva';case'downloading':return'Baixando atualização';case'copying':return'Preparando arquivo baixado';case'verifying':return'Conferindo APK e assinatura';case'opening-installer':return'Abrindo instalador Android';case'ready':return'Instalador aberto';default:return'Atualizando aplicativo'}}
const DOWNLOAD_PHASES=['downloading','downloading-system','downloading-http'];
const STAGE:Record<string,number>={'refreshing-manifest':1,'preparing-backup':2,'awaiting-permission':3,connecting:4,downloading:5,'downloading-system':5,'downloading-http':5,copying:6,verifying:7,'opening-installer':8,ready:8};
function useTransferEstimate(progress:ApkDownloadProgress|null){const previous=useRef<{at:number;bytes:number}|null>(null),speedRef=useRef(0),[speed,setSpeed]=useState(0);useEffect(()=>{if(!progress||![...DOWNLOAD_PHASES,'copying'].includes(progress.phase)){if(progress?.phase==='connecting'||progress?.phase==='refreshing-manifest'){previous.current=null;speedRef.current=0;setSpeed(0)}return}const now=Date.now(),bytes=Math.max(0,Number(progress.downloadedBytes||0)),prev=previous.current;if(prev&&bytes>=prev.bytes){const elapsed=(now-prev.at)/1000;if(elapsed>=.25){const instant=(bytes-prev.bytes)/elapsed;if(instant>0){speedRef.current=speedRef.current?speedRef.current*.68+instant*.32:instant;setSpeed(speedRef.current)}}}previous.current={at:now,bytes}},[progress]);const etaSeconds=useMemo(()=>!progress||speed<=0||progress.totalBytes<=progress.downloadedBytes||![...DOWNLOAD_PHASES,'copying'].includes(progress.phase)?null:(progress.totalBytes-progress.downloadedBytes)/speed,[progress,speed]);return{speed,etaSeconds}}
function useUpdatePhaseActivity(progress:ApkDownloadProgress|null){const started=useRef(Date.now()),last=useRef({at:Date.now(),bytes:Number(progress?.downloadedBytes||0)}),[now,setNow]=useState(Date.now());useEffect(()=>{const at=Date.now();started.current=at;last.current={at,bytes:Number(progress?.downloadedBytes||0)};setNow(at)},[progress?.phase]);useEffect(()=>{const bytes=Number(progress?.downloadedBytes||0);if(bytes!==last.current.bytes)last.current={at:Date.now(),bytes}},[progress?.downloadedBytes]);useEffect(()=>{if(!progress||progress.phase==='ready')return;const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[progress?.phase]);return{phaseElapsedSeconds:Math.max(0,(now-started.current)/1000),stalledSeconds:Math.max(0,(now-last.current.at)/1000)}}
export function UpdateTransferProgressV4010({progress,targetVersion,compact=false,completed=false}:{progress:ApkDownloadProgress|null;targetVersion?:string|null;compact?:boolean;completed?:boolean}){const{speed,etaSeconds}=useTransferEstimate(progress),{phaseElapsedSeconds,stalledSeconds}=useUpdatePhaseActivity(progress),overall=completed?100:updateOverallPercent(progress),stage=completed?'Atualização concluída':updateStageLabel(progress),downloadActive=Boolean(progress&&DOWNLOAD_PHASES.includes(progress.phase)),stageIndex=completed?8:STAGE[progress?.phase||'']||1,stageTotal=8,elapsed=formatActivityDuration(phaseElapsedSeconds);let detail='O BuildMaster acompanha cada etapa até entregar o APK ao instalador.';
if(completed)detail=`BuildMaster v${targetVersion||'nova'} instalado com sucesso.`;else if(progress?.phase==='ready')detail='O APK foi validado. Confirme “Atualizar” no instalador do Android; essa etapa final é controlada pelo sistema.';else if(progress?.phase==='opening-installer')detail='Download e validação concluídos. Entregando o APK ao instalador do Android.';else if(progress?.phase==='verifying')detail=`Conferindo SHA-256, tamanho, pacote e versão • ${elapsed} nesta etapa.`;else if(progress?.phase==='copying')detail=`Copiando o APK para a área segura do instalador • ${elapsed}.`;else if(progress?.phase==='awaiting-permission')detail='Ative “Permitir desta fonte” e volte ao BuildMaster para continuar.';else if(progress?.phase==='preparing-backup')detail=`Criando cópia de recuperação • ${elapsed}.`;else if(progress?.phase==='refreshing-manifest')detail=`Consultando versão, tamanho e assinatura • ${elapsed}.`;else if(progress?.phase==='connecting')detail=`Aguardando resposta do servidor oficial • ${elapsed}.`;else if(downloadActive&&progress)detail=progress.downloadedBytes<=0?`Aguardando os primeiros dados há ${elapsed}. O download continua ativo.`:`${formatProgressBytes(progress.downloadedBytes)}${progress.totalBytes>0?` de ${formatProgressBytes(progress.totalBytes)}`:''}${stalledSeconds>=5?` • sem novos bytes há ${formatActivityDuration(stalledSeconds)}`:''}`;
const activityMeta=completed?`Etapa ${stageTotal} de ${stageTotal}`:downloadActive&&speed>0?`Etapa ${stageIndex} de ${stageTotal} • ${formatProgressBytes(speed)}/s${etaSeconds?` • faltam ${formatRemainingTime(etaSeconds)}`:''}`:`Etapa ${stageIndex} de ${stageTotal} • ${elapsed} nesta etapa`;
return <section className={`v4020-operation-progress v4020-update-progress ${compact?'is-compact':''} ${completed?'is-complete':''}`} role="status" aria-live="polite" aria-label={`Atualização do aplicativo: ${overall}%`}><div className="v4020-progress-icon">{completed?<CheckCircle2 size={20}/>:progress?.phase==='ready'||progress?.phase==='opening-installer'?<Smartphone size={20}/>:progress?.phase==='verifying'?<ShieldCheck size={20}/>:downloadActive||progress?.phase==='copying'?<Download size={20}/>:<Loader2 className="spin" size={20}/>}</div><div className="v4020-progress-main"><div className="v4020-progress-heading"><div><strong>{stage}</strong>{targetVersion&&<span>v{targetVersion}</span>}</div><b>{overall}%</b></div><div className="v4020-progress-track"><i style={{width:`${overall}%`}}/></div><div className="v4020-progress-meta"><span>{detail}</span><span><Clock3 size={12}/> {activityMeta}</span></div></div></section>}
export type ReaderProgressSnapshotV4010={percent:number;phase:string;detail:string;startedAt:number;completed?:number;total?:number;deadlineMs?:number};
export function ReaderProgressBarV4010({progress}:{progress:ReaderProgressSnapshotV4010|null}){const[now,setNow]=useState(Date.now()),percent=clamp(progress?.percent??0);useEffect(()=>{setNow(Date.now());if(!progress||percent>=100)return;const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[progress?.startedAt,percent]);const elapsedSeconds=progress?Math.max(0,(now-progress.startedAt)/1000):0,deadlineSeconds=Math.max(30,Number(progress?.deadlineMs||90_000)/1000),completed=Math.max(0,Number(progress?.completed||0)),total=Math.max(0,Number(progress?.total||0)),byFields=completed>0&&total>completed?(elapsedSeconds/completed)*(total-completed):null,safeRemaining=Math.max(0,deadlineSeconds-elapsedSeconds),eta=progress&&percent>=5&&percent<100?Math.min(safeRemaining,byFields&&Number.isFinite(byFields)?Math.max(5,byFields):safeRemaining):null;return <div className="v4020-reader-progress" aria-label={`Progresso da leitura: ${Math.round(percent)}%`}><div className="v4020-progress-heading"><div><strong>{progress?.phase||'Preparando leitura'}</strong>{progress?.total?<span>{Math.min(progress.completed??0,progress.total)}/{progress.total} campos</span>:null}</div><b>{Math.round(percent)}%</b></div><div className="v4020-progress-track"><i style={{width:`${percent}%`}}/></div><div className="v4020-progress-meta"><span>{progress?.detail||'Preparando o print.'}</span>{eta?<span><Clock3 size={12}/> estimativa: {formatRemainingTime(eta)}</span>:null}</div></div>}
