-- BuildMaster Elite Tático v26.72
-- Contas fechadas por usuário, licença com prazo e separação de dados.

create extension if not exists citext;

create table if not exists public.buildmaster_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username citext not null unique,
  display_name text not null default '',
  role text not null default 'user' check (role in ('admin', 'user')),
  status text not null default 'active' check (status in ('active', 'suspended', 'blocked')),
  plan text not null default 'premium',
  expires_at timestamptz,
  max_devices integer not null default 1 check (max_devices between 1 and 10),
  offline_grace_hours integer not null default 24 check (offline_grace_hours between 0 and 168),
  created_by uuid references auth.users(id) on delete set null,
  last_access_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.buildmaster_devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.buildmaster_profiles(id) on delete cascade,
  device_id text not null,
  device_name text not null default 'Aparelho',
  platform text not null default 'unknown',
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  unique (user_id, device_id)
);

create table if not exists public.user_vault_snapshots (
  user_id uuid primary key references public.buildmaster_profiles(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.buildmaster_admin_audit (
  id bigint generated by default as identity primary key,
  admin_id uuid references public.buildmaster_profiles(id) on delete set null,
  target_user_id uuid references public.buildmaster_profiles(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.buildmaster_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists buildmaster_profiles_touch on public.buildmaster_profiles;
create trigger buildmaster_profiles_touch
before update on public.buildmaster_profiles
for each row execute function public.buildmaster_touch_updated_at();

create or replace function public.buildmaster_handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_username text;
begin
  requested_username := lower(coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)));
  insert into public.buildmaster_profiles (
    id, username, display_name, role, status, plan, expires_at, max_devices, offline_grace_hours
  ) values (
    new.id,
    requested_username,
    coalesce(nullif(new.raw_user_meta_data->>'display_name', ''), requested_username),
    'user',
    case when coalesce(new.raw_app_meta_data->>'buildmaster_managed', 'false') = 'true' then 'active' else 'suspended' end,
    coalesce(nullif(new.raw_user_meta_data->>'plan', ''), 'premium'),
    nullif(new.raw_user_meta_data->>'expires_at', '')::timestamptz,
    greatest(1, least(10, coalesce((new.raw_user_meta_data->>'max_devices')::integer, 1))),
    greatest(0, least(168, coalesce((new.raw_user_meta_data->>'offline_grace_hours')::integer, 24)))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists buildmaster_auth_user_created on auth.users;
create trigger buildmaster_auth_user_created
after insert on auth.users
for each row execute function public.buildmaster_handle_new_auth_user();

create or replace function public.buildmaster_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.buildmaster_profiles
    where id = auth.uid() and role = 'admin' and status = 'active'
  );
$$;

create or replace function public.buildmaster_validate_license_and_register_device(
  p_device_id text,
  p_device_name text default 'Aparelho',
  p_platform text default 'unknown'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  profile_row public.buildmaster_profiles%rowtype;
  existing_device public.buildmaster_devices%rowtype;
  active_devices integer;
begin
  if auth.uid() is null then
    raise exception 'Sessão inválida.' using errcode = 'P0001';
  end if;

  select * into profile_row
  from public.buildmaster_profiles
  where id = auth.uid()
  for update;

  if not found then
    raise exception 'Perfil da conta não encontrado.' using errcode = 'P0001';
  end if;
  if profile_row.status = 'blocked' then
    raise exception 'Esta conta foi bloqueada pelo administrador.' using errcode = 'P0001';
  end if;
  if profile_row.status = 'suspended' then
    raise exception 'Esta conta está suspensa.' using errcode = 'P0001';
  end if;
  if profile_row.expires_at is not null and profile_row.expires_at <= now() then
    raise exception 'Seu prazo de acesso terminou.' using errcode = 'P0001';
  end if;

  select * into existing_device
  from public.buildmaster_devices
  where user_id = auth.uid() and device_id = p_device_id;

  if not found or existing_device.revoked_at is not null then
    select count(*) into active_devices
    from public.buildmaster_devices
    where user_id = auth.uid() and revoked_at is null;

    if active_devices >= profile_row.max_devices then
      raise exception 'Limite de aparelhos atingido. Peça ao administrador para desconectar um aparelho.' using errcode = 'P0001';
    end if;
  end if;

  insert into public.buildmaster_devices (user_id, device_id, device_name, platform, first_seen_at, last_seen_at, revoked_at)
  values (auth.uid(), p_device_id, left(coalesce(p_device_name, 'Aparelho'), 120), left(coalesce(p_platform, 'unknown'), 240), now(), now(), null)
  on conflict (user_id, device_id) do update set
    device_name = excluded.device_name,
    platform = excluded.platform,
    last_seen_at = now(),
    revoked_at = null;

  update public.buildmaster_profiles set last_access_at = now() where id = auth.uid();

  return jsonb_build_object(
    'id', profile_row.id,
    'username', profile_row.username,
    'display_name', profile_row.display_name,
    'role', profile_row.role,
    'status', profile_row.status,
    'plan', profile_row.plan,
    'expires_at', profile_row.expires_at,
    'max_devices', profile_row.max_devices,
    'offline_grace_hours', profile_row.offline_grace_hours,
    'last_access_at', now()
  );
end;
$$;

grant execute on function public.buildmaster_validate_license_and_register_device(text, text, text) to authenticated;
grant execute on function public.buildmaster_is_admin() to authenticated;

alter table public.buildmaster_profiles enable row level security;
alter table public.buildmaster_devices enable row level security;
alter table public.user_vault_snapshots enable row level security;
alter table public.buildmaster_admin_audit enable row level security;

grant select on public.buildmaster_profiles to authenticated;
grant select on public.buildmaster_devices to authenticated;
grant select, insert, update, delete on public.user_vault_snapshots to authenticated;
grant select on public.buildmaster_admin_audit to authenticated;

-- Usuário comum enxerga somente o próprio perfil.
drop policy if exists buildmaster_profile_self_select on public.buildmaster_profiles;
create policy buildmaster_profile_self_select on public.buildmaster_profiles
for select to authenticated using (id = auth.uid() or public.buildmaster_is_admin());

drop policy if exists buildmaster_device_self_select on public.buildmaster_devices;
create policy buildmaster_device_self_select on public.buildmaster_devices
for select to authenticated using (user_id = auth.uid() or public.buildmaster_is_admin());

-- Cofre em nuvem totalmente separado por usuário.
drop policy if exists buildmaster_vault_self_select on public.user_vault_snapshots;
create policy buildmaster_vault_self_select on public.user_vault_snapshots
for select to authenticated using (user_id = auth.uid());

drop policy if exists buildmaster_vault_self_insert on public.user_vault_snapshots;
create policy buildmaster_vault_self_insert on public.user_vault_snapshots
for insert to authenticated with check (user_id = auth.uid());

drop policy if exists buildmaster_vault_self_update on public.user_vault_snapshots;
create policy buildmaster_vault_self_update on public.user_vault_snapshots
for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists buildmaster_vault_self_delete on public.user_vault_snapshots;
create policy buildmaster_vault_self_delete on public.user_vault_snapshots
for delete to authenticated using (user_id = auth.uid());

-- O log administrativo só é lido por administradores; gravações normais ocorrem pela Edge Function.
drop policy if exists buildmaster_audit_admin_select on public.buildmaster_admin_audit;
create policy buildmaster_audit_admin_select on public.buildmaster_admin_audit
for select to authenticated using (public.buildmaster_is_admin());

-- A trigger nunca concede administrador por user_metadata e suspende cadastros que não vieram da função administrativa.
-- Depois de criar a primeira conta no painel Authentication do Supabase, promova-a manualmente:
-- update public.buildmaster_profiles set role = 'admin', expires_at = null where username = 'seu_usuario';
