-- BuildMaster Elite Tático v29.10 — Blocos 12 e 13
-- Administração auditável, controle individual de aparelhos, política mínima de APK
-- e base de governança para canais de atualização.

alter table public.buildmaster_admin_audit
  add column if not exists outcome text not null default 'success'
    check (outcome in ('success', 'denied', 'error')),
  add column if not exists app_version text,
  add column if not exists request_id uuid;

create index if not exists buildmaster_admin_audit_created_idx
  on public.buildmaster_admin_audit(created_at desc);
create index if not exists buildmaster_admin_audit_target_idx
  on public.buildmaster_admin_audit(target_user_id, created_at desc);
create unique index if not exists buildmaster_admin_audit_request_idx
  on public.buildmaster_admin_audit(request_id)
  where request_id is not null;

-- A implantação da v29.10 não bloqueia a v29.00 antes de o novo APK chegar aos
-- aparelhos. Depois da validação, o administrador pode elevar min_app_version
-- para 29.10.0 diretamente no painel protegido por MFA.
update public.buildmaster_security_settings
set min_app_version = case
      when string_to_array(regexp_replace(min_app_version, '[^0-9.]', '', 'g'), '.')::int[]
           < array[29,0,0] then '29.00.0'
      else min_app_version
    end,
    allow_legacy_clients = false,
    require_device_proof = true,
    admin_mfa_required = true,
    updated_at = now()
where id = 1;

create table if not exists public.buildmaster_release_governance (
  id smallint primary key default 1 check (id = 1),
  stable_rollout_percent integer not null default 100 check (stable_rollout_percent between 1 and 100),
  beta_rollout_percent integer not null default 100 check (beta_rollout_percent between 1 and 100),
  stable_paused boolean not null default false,
  beta_paused boolean not null default false,
  last_known_good_version text,
  rollback_version text,
  updated_by uuid references public.buildmaster_profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into public.buildmaster_release_governance (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.buildmaster_release_history (
  id bigint generated by default as identity primary key,
  version text not null,
  version_code bigint not null,
  build_id text not null,
  channel text not null check (channel in ('stable', 'beta')),
  rollout_percent integer not null default 100 check (rollout_percent between 1 and 100),
  status text not null default 'published' check (status in ('testing', 'published', 'paused', 'rolled_back', 'failed')),
  release_tag text,
  apk_checksum text,
  notes jsonb not null default '[]'::jsonb,
  published_by uuid references public.buildmaster_profiles(id) on delete set null,
  published_at timestamptz not null default now(),
  unique (version_code, channel)
);

create index if not exists buildmaster_release_history_channel_idx
  on public.buildmaster_release_history(channel, published_at desc);

alter table public.buildmaster_release_governance enable row level security;
alter table public.buildmaster_release_history enable row level security;
revoke all on public.buildmaster_release_governance from anon, authenticated;
revoke all on public.buildmaster_release_history from anon, authenticated;

-- Edge Functions com service_role gerenciam as tabelas. A leitura do painel
-- administrativo continua exigindo conta admin e AAL2 no servidor.
