import { planAdaptiveImageSize } from '@/lib/invisibleOptimizationV3820';
export type ImageEnhancement='original'|'color'|'contrast'|'sharp'|'binary'|'inverted';
type PixelBuffer=Uint8ClampedArray<ArrayBufferLike>;type DecodedBitmap=ImageBitmap|(HTMLImageElement&{close?:()=>void});type ImageDimensions={width:number;height:number};
const DIMENSION_HEADER_BYTES=128*1024;
function normalizeLine(line:string){return line.replace(/\s+/g,' ').trim()}
export function mergeOcrTexts(...texts:string[]){const lines=new Map<string,string>();for(const text of texts)for(const line of text.split(/\r?\n/).map(normalizeLine).filter(Boolean)){const key=line.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'');if(key&&!lines.has(key))lines.set(key,line)}return Array.from(lines.values()).join('\n')}
function validDimensions(width:number,height:number):ImageDimensions|null{return Number.isFinite(width)&&Number.isFinite(height)&&width>0&&height>0&&width<=20_000&&height<=20_000?{width,height}:null}
export async function readImageDimensions(file:File|Blob):Promise<ImageDimensions|null>{try{const h=new Uint8Array(await file.slice(0,Math.min(file.size,DIMENSION_HEADER_BYTES)).arrayBuffer());if(h.length>=24&&h[0]===0x89&&h[1]===0x50&&h[2]===0x4e&&h[3]===0x47){const v=new DataView(h.buffer,h.byteOffset,h.byteLength);return validDimensions(v.getUint32(16,false),v.getUint32(20,false))}if(h.length>=12&&h[0]===0xff&&h[1]===0xd8){const sof=new Set([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf]);let o=2;while(o+8<h.length){if(h[o]!==0xff){o++;continue}while(o<h.length&&h[o]===0xff)o++;const marker=h[o++];if(marker===0xd8||marker===0xd9||(marker>=0xd0&&marker<=0xd7))continue;if(o+1>=h.length)break;const len=(h[o]<<8)|h[o+1];if(len<2||o+len>h.length)break;if(sof.has(marker)&&len>=7)return validDimensions((h[o+5]<<8)|h[o+6],(h[o+3]<<8)|h[o+4]);o+=len}}if(h.length>=30&&String.fromCharCode(...h.slice(0,4))==='RIFF'&&String.fromCharCode(...h.slice(8,12))==='WEBP'&&String.fromCharCode(...h.slice(12,16))==='VP8X')return validDimensions(1+h[24]+(h[25]<<8)+(h[26]<<16),1+h[27]+(h[28]<<8)+(h[29]<<16))}catch{}return null}
async function htmlImageFallback(file:File|Blob):Promise<DecodedBitmap|null>{if(typeof document==='undefined'||typeof URL==='undefined'||!URL.createObjectURL)return null;return new Promise(resolve=>{const url=URL.createObjectURL(file),image=new Image();let settled=false;const finish=(value:DecodedBitmap|null)=>{if(settled)return;settled=true;globalThis.clearTimeout(timer);if(!value)URL.revokeObjectURL(url);resolve(value)},timer=globalThis.setTimeout(()=>finish(null),8_000);image.onload=()=>{const decoded=image as DecodedBitmap;decoded.close=()=>{image.src='';URL.revokeObjectURL(url)};finish(decoded)};image.onerror=()=>finish(null);image.src=url})}
async function bitmapWithTimeout(factory:()=>Promise<ImageBitmap>):Promise<ImageBitmap|null>{return new Promise(resolve=>{let settled=false;const timer=globalThis.setTimeout(()=>{if(!settled){settled=true;resolve(null)}},8_000);factory().then(value=>{if(settled){value.close?.();return}settled=true;globalThis.clearTimeout(timer);resolve(value)},()=>{if(!settled){settled=true;globalThis.clearTimeout(timer);resolve(null)}})})}
async function imageToBitmap(file:File|Blob):Promise<DecodedBitmap|null>{if(typeof document==='undefined')return null;if(typeof createImageBitmap!=='undefined'){const bitmap=await bitmapWithTimeout(()=>createImageBitmap(file));if(bitmap)return bitmap}return htmlImageFallback(file)}
async function resizedBitmap(file:File|Blob,plan:{width:number;height:number}){if(typeof createImageBitmap==='undefined')return null;return bitmapWithTimeout(()=>createImageBitmap(file, { resizeWidth: plan.width, resizeHeight: plan.height,resizeQuality:'high'}))}
async function croppedBitmap(file:File|Blob,cropX:number,cropY:number,cropW:number,cropH:number,plan:{width:number;height:number}){if(typeof createImageBitmap==='undefined')return null;return bitmapWithTimeout(()=>createImageBitmap(file, cropX, cropY, cropW, cropH, { resizeWidth: plan.width, resizeHeight: plan.height,resizeQuality:'high'}))}
function clampByte(value:number){return Math.max(0,Math.min(255,Math.round(value)))}function luminance(r:number,g:number,b:number){return r*.299+g*.587+b*.114}
function grayscaleInPlace(data:PixelBuffer){for(let i=0;i<data.length;i+=4){const gray=clampByte(luminance(data[i],data[i+1],data[i+2]));data[i]=gray;data[i+1]=gray;data[i+2]=gray}}
function darkRatio(data:PixelBuffer){let sampled=0,dark=0;for(let i=0;i<data.length;i+=32){sampled++;if(luminance(data[i],data[i+1],data[i+2])<82)dark++}return sampled?dark/sampled:0}
function brightSignalInPlace(data:PixelBuffer){for(let i=0;i<data.length;i+=4){const v=Math.max(data[i],data[i+1],data[i+2]);data[i]=v;data[i+1]=v;data[i+2]=v}}
function otsuThreshold(data:PixelBuffer){const histogram=new Uint32Array(256);let pixels=0,total=0;for(let i=0;i<data.length;i+=4){histogram[data[i]]++;pixels++}if(!pixels)return 128;for(let v=0;v<256;v++)total+=v*histogram[v];let bw=0,bs=0,best=-1,result=128;for(let t=0;t<256;t++){bw+=histogram[t];if(!bw)continue;const fw=pixels-bw;if(!fw)break;bs+=t*histogram[t];const bm=bs/bw,fm=(total-bs)/fw,between=bw*fw*(bm-fm)**2;if(between>best){best=between;result=t}}return result}
function applyContrast(data:PixelBuffer,factor:number,lift:number){for(let i=0;i<data.length;i+=4){const v=clampByte((data[i]-128)*factor+128+lift);data[i]=v;data[i+1]=v;data[i+2]=v}}
function sharpenGrayscaleInPlace(data:PixelBuffer,width:number,height:number){if(width<3||height<3)return;const source=new Uint8ClampedArray(data);for(let y=1;y<height-1;y++)for(let x=1;x<width-1;x++){const c=(y*width+x)*4,v=clampByte(source[c]*5-source[c-4]-source[c+4]-source[c-width*4]-source[c+width*4]);data[c]=v;data[c+1]=v;data[c+2]=v}}
function enhancePixels(imageData:ImageData,mode:ImageEnhancement){const{width,height,data}=imageData;if(mode==='original')return;if(mode==='color'){for(let i=0;i<data.length;i+=4){const gray=luminance(data[i],data[i+1],data[i+2]);data[i]=clampByte((data[i]-gray)*.72+gray*1.06+5);data[i+1]=clampByte((data[i+1]-gray)*.72+gray*1.06+5);data[i+2]=clampByte((data[i+2]-gray)*.72+gray*1.06+5)}return}if(mode==='contrast'||mode==='sharp'){grayscaleInPlace(data);applyContrast(data,mode==='sharp'?2.08:1.72,mode==='sharp'?20:15);if(mode==='sharp')sharpenGrayscaleInPlace(data,width,height);return}const bright=darkRatio(data)>=.58;if(bright)brightSignalInPlace(data);else grayscaleInPlace(data);const threshold=otsuThreshold(data);for(let i=0;i<data.length;i+=4){const foreground=bright?data[i]>threshold:data[i]<=threshold,v=mode==='inverted'?(foreground?0:255):(foreground?255:0);data[i]=v;data[i+1]=v;data[i+2]=v}}
function canvasBlob(canvas:HTMLCanvasElement,fallback:File|Blob):Promise<Blob|File>{return new Promise(resolve=>{let settled=false;const timer=globalThis.setTimeout(()=>{if(!settled){settled=true;resolve(fallback)}},6_000);canvas.toBlob(blob=>{if(settled)return;settled=true;globalThis.clearTimeout(timer);resolve(blob??fallback)},'image/png',.98)})}
export function expandOcrRegion(region:{x:number;y:number;w:number;h:number},horizontal=.04,vertical=.025){const x=Math.max(0,region.x-horizontal),y=Math.max(0,region.y-vertical),right=Math.min(1,region.x+region.w+horizontal),bottom=Math.min(1,region.y+region.h+vertical);return{x,y,w:Math.max(.01,right-x),h:Math.max(.01,bottom-y)}}

export async function preprocessImage(file:File|Blob,mode:ImageEnhancement='contrast'):Promise<Blob|File>{
 const dimensions=await readImageDimensions(file),planned=dimensions?planAdaptiveImageSize(dimensions.width,dimensions.height,{workload: 'ocr-full', preferredLongestSide: 1400,minScale:.1,maxScale: 1}):null;let bitmap:DecodedBitmap|null=planned?await resizedBitmap(file,planned):null;if(!bitmap)bitmap=await imageToBitmap(file);if(!bitmap)return file;const plan=planned??planAdaptiveImageSize(bitmap.width,bitmap.height,{workload: 'ocr-full', preferredLongestSide: 1400,minScale:.1,maxScale: 1}),canvas=document.createElement('canvas');
 try{canvas.width=plan.width;canvas.height=plan.height;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)return file;ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const imageData=ctx.getImageData(0,0,canvas.width,canvas.height);enhancePixels(imageData,mode);ctx.putImageData(imageData,0,0);return await canvasBlob(canvas,file)}finally{bitmap.close?.();canvas.width = 1; canvas.height = 1;}
}

export async function cropImage(file:File|Blob,region:{x:number;y:number;w:number;h:number},widthTarget=1900,mode:ImageEnhancement='contrast'):Promise<Blob|File>{
 if(typeof document==='undefined')return file;const dimensions=await readImageDimensions(file),safeTarget=Math.min(Math.max(720,widthTarget),1900);let bitmap:DecodedBitmap|null=null,plan:{width:number;height:number}|null=null,fallbackCrop:{x:number;y:number;w:number;h:number}|null=null;if(dimensions){const cropX=Math.max(0,Math.round(dimensions.width*region.x)),cropY=Math.max(0,Math.round(dimensions.height*region.y)),cropW=Math.max(1,Math.min(dimensions.width-cropX,Math.round(dimensions.width*region.w))),cropH=Math.max(1,Math.min(dimensions.height-cropY,Math.round(dimensions.height*region.h)));plan=planAdaptiveImageSize(cropW,cropH,{workload:'ocr-crop',preferredLongestSide: safeTarget, minScale: 0.25, maxScale: 4.2});bitmap=await croppedBitmap(file,cropX,cropY,cropW,cropH,plan)}if(!bitmap){bitmap=await imageToBitmap(file);if(!bitmap)return file;const cropX=Math.max(0,Math.round(bitmap.width*region.x)),cropY=Math.max(0,Math.round(bitmap.height*region.y)),cropW=Math.max(1,Math.min(bitmap.width-cropX,Math.round(bitmap.width*region.w))),cropH=Math.max(1,Math.min(bitmap.height-cropY,Math.round(bitmap.height*region.h)));plan=planAdaptiveImageSize(cropW,cropH,{workload:'ocr-crop',preferredLongestSide: safeTarget, minScale: 0.25, maxScale: 4.2});fallbackCrop={x:cropX,y:cropY,w:cropW,h:cropH}}const canvas=document.createElement('canvas');
 try{canvas.width=plan!.width;canvas.height=plan!.height;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)return file;ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';if(fallbackCrop)ctx.drawImage(bitmap,fallbackCrop.x,fallbackCrop.y,fallbackCrop.w,fallbackCrop.h,0,0,canvas.width,canvas.height);else ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const imageData=ctx.getImageData(0,0,canvas.width,canvas.height);enhancePixels(imageData,mode);ctx.putImageData(imageData,0,0);return await canvasBlob(canvas,file)}finally{bitmap.close?.();canvas.width = 1; canvas.height = 1;}
}
