import type { OcrZone } from '@/lib/ocr';
import type { PositionCode, PositionProficiencyLevel } from '@/lib/analyzerDomain';
export const POSITION_PROFICIENCY_VISION_R416_VERSION='40.80-r416-position-proficiency-vision-v1' as const;
type Box=[number,number,number,number];
const CELLS:Record<PositionCode,Box>={LWF:[.02,.02,.24,.29],CF:[.27,.02,.73,.15],RWF:[.76,.02,.98,.29],SS:[.27,.16,.73,.29],LMF:[.02,.31,.24,.72],AMF:[.27,.31,.73,.43],CMF:[.27,.44,.73,.57],RMF:[.76,.31,.98,.72],DMF:[.27,.58,.73,.72],LB:[.02,.74,.24,.98],CB:[.27,.74,.73,.86],RB:[.76,.74,.98,.98],GK:[.27,.87,.73,.98]};
export type PositionProficiencyVisualR416={level:PositionProficiencyLevel;confidence:number;greenScore:number};export type PositionProficiencyGridR416=Partial<Record<PositionCode,PositionProficiencyVisualR416>>;
function median(v:number[]){if(!v.length)return 0;const a=[...v].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
function sample(d:Uint8ClampedArray,w:number,h:number,b:Box){const[x1,y1,x2,y2]=b,xs=Math.floor(w*(x1+(x2-x1)*.16)),xe=Math.ceil(w*(x2-(x2-x1)*.16)),ys=Math.floor(h*(y1+(y2-y1)*.18)),ye=Math.ceil(h*(y2-(y2-y1)*.18)),s:number[]=[];for(let y=ys;y<ye;y+=2)for(let x=xs;x<xe;x+=2){const i=(y*w+x)*4,r=d[i],g=d[i+1],bb=d[i+2];if(Math.max(r,g,bb)>185)continue;s.push(g-(r+bb)/2);}return median(s);}
export async function readPositionProficiencyGridR416(file:File|Blob,zone:OcrZone):Promise<PositionProficiencyGridR416|null>{if(typeof document==='undefined'||typeof createImageBitmap==='undefined')return null;const bitmap=await createImageBitmap(file).catch(()=>null);if(!bitmap)return null;const canvas=document.createElement('canvas');try{const sx=Math.max(0,Math.round(bitmap.width*zone.x)),sy=Math.max(0,Math.round(bitmap.height*zone.y)),sw=Math.max(1,Math.round(bitmap.width*zone.w)),sh=Math.max(1,Math.round(bitmap.height*zone.h));canvas.width=620;canvas.height=Math.max(300,Math.round(620*sh/sw));const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)return null;ctx.drawImage(bitmap,sx,sy,sw,sh,0,0,canvas.width,canvas.height);const img=ctx.getImageData(0,0,canvas.width,canvas.height),raw=(Object.entries(CELLS) as Array<[PositionCode,Box]>).map(([code,box])=>({code,score:sample(img.data,canvas.width,canvas.height,box)})),ordered=raw.map(x=>x.score).sort((a,b)=>a-b),baseline=median(ordered.slice(0,Math.max(3,Math.floor(ordered.length*.45)))),peak=Math.max(...ordered),span=Math.max(1,peak-baseline),out:PositionProficiencyGridR416={};for(const item of raw){const delta=item.score-baseline;let level:PositionProficiencyLevel='LOW';if(delta>=Math.max(15,span*.62))level='HIGH';else if(delta>=Math.max(7,span*.24))level='INTERMEDIATE';const boundary=level==='HIGH'?Math.max(15,span*.62):level==='INTERMEDIATE'?Math.max(7,span*.24):0,distance=Math.abs(delta-boundary);out[item.code]={level,confidence:Math.max(60,Math.min(96,Math.round(72+distance*1.4))),greenScore:Math.round(item.score*10)/10};}return out;}finally{bitmap.close?.();canvas.width=1;canvas.height=1;}}
